### ISSUE TITLE
Convert ttf to fnt

### ISSUE THREAD

**Issue by chahatbahl** [jimp-dev/jimp#1002]
Go to website https://ttf2fnt.com/
Upload your font in ttf format
Choose color, size, ... and click convert
You will get fnt format which works is bitmap format

It works !!!

**Comment by MarkShawn2020** [comment]
it won't work if your file is large and it would just pass to convert those character like chinese

**Comment by bierzorutas** [comment]
Same problem here with, with something simplier like opening of question marks or exclamations marks, that web dont do it..

**Comment by abdelmark** [comment]
@kedeng In Bmfont go to export settings, format, select XML and png texture. The exported file will include an fnt file plus and png file, upload both to your Jimp project. From your code set the fnt file path only.
