### ISSUE TITLE
DoS attack vulnerability

### ISSUE THREAD

**Issue by Sly-Little-Fox** [jimp-dev/jimp#1003]
# Expected Behavior

`Jimp.read` promise should be rejected in case of errors.

# Current Behavior

`Jimp.read` throws an error when providing a site with infinite redirect. Can be used to take an app down.

# Failure Information (for bugs)

An uncaught exception is thrown inside Jimp. 

## Steps to Reproduce
Step 1. Run this code and see what happens:
```js
var Jimp = require('jimp');

Jimp.read('https://infinity.👋🏼.ml').then(async (image) => {
  // Code is not necessary here
}).catch((e) => {
  console.error(e);
});
```
 
infinity.👋🏼.ml is a site with infinite redirect. 

**Screenshots**
No screenshots

## Context

- Jimp Version: 0.16.1
- Operating System: Linux
- Node version: 14.15.5

## Failure Logs

```
TypeError: Cannot read property 'toLowerCase' of null
    at phin (/tmp/node_modules/phin/lib/phin.compiled.js:1:744)
    at module.exports (/tmp/node_modules/@jimp/core/dist/request.js:44:5)
    at loadFromURL (/tmp/node_modules/@jimp/core/dist/index.js:104:27)
    at /tmp/node_modules/@jimp/core/dist/index.js:111:14
    at /tmp/node_modules/@jimp/core/dist/request.js:48:9
    at IncomingMessage.<anonymous> (/tmp/node_modules/phin/lib/phin.compiled.js:1:2100)
```

**Comment by Explosion-Scratch** [comment]
😭 Happened to me too on my API.

**Comment by Sly-Little-Fox** [comment]
The error is from phin, jimp just doesn't handle it.

**Comment by Sly-Little-Fox** [comment]
Let me try to fix it.

**Comment by Sly-Little-Fox** [comment]
What's wrong with it :angry:

**Comment by Sly-Little-Fox** [comment]
Done. Let me publish my patch...

**Comment by Sly-Little-Fox** [comment]
Patch: https://gist.github.com/Sly-Little-Fox/a476422c45b8ed868f196a1647594d22

**Comment by Sly-Little-Fox** [comment]
It crashes if you provide it any redirect. I am going to patch phin itself.

**Comment by Explosion-Scratch** [comment]
@oliver-moran Please look at/review this PR!

**Comment by ethanent** [comment]
Thanks for the suggestion. I've made an issue here: https://github.com/ethanent/phin/issues/78

**Comment by ethanent** [comment]
Actually, though, making that change at Phin won't solve the problem as the redirect following behavior is currently handled by Jimp, specifically here: https://github.com/oliver-moran/jimp/blob/53ff9d1266207f7f674233f465ec358274510511/packages/core/src/index.js#L67

I recommend using Phin's `followRedirects` option instead, and solving the problem there instead. This will be a more elegant solution.

**Comment by Sly-Little-Fox** [comment]
Actually it looks like this has been fixed in Phin. I'm not sure that fully though, so will keep the issue open.

**Comment by alenocera** [comment]
Hi, idk if it is related but I've also this one about DoS vulnerability:
Introduced through: jimp@0.16.2 > @jimp/custom@0.16.2 > @jimp/core@0.16.2 > file-type@9.0.0

Remediation (provided by Snyk)
Upgrade `file-type` to version 16.5.4, 17.1.3 or higher.

Can be possible upgrade these lib in order to avoid this issue?

Thanks!

**Comment by hipstersmoothie** [comment]
We just upgraded file type so this might not be an issue anymore? happy to accept a PR to fix

**Comment by hipstersmoothie** [comment]
file type is upgraded and I'm getting in @Sly-Little-Fox's patch
