### ISSUE TITLE
rotate(0) and rotate(0,false) both manipulate the image and probably shouldn't

### ISSUE THREAD

**Issue by jonahlibrach** [jimp-dev/jimp#1007]
# Expected Behavior

Console should output:

`[252,71]`
`[252,71]`

# Current Behavior

Tried this on multiple images, error happens in both:

`[252,71]`
`[254,72]`

# Failure Information (for bugs)

## Steps to Reproduce

```
let jimp = require('jimp');

let x = jimp.read('myImage.png').then(
  image => {
    console.log([image.bitmap.width, image.bitmap.height]);
    image.rotate(0);
    console.log([image.bitmap.width, image.bitmap.height]);
  }
)
```

## Context

- Jimp Version: 0.16.1
- Operating System: macOS Mojave Version 10.14.1
- Node version: 14.12.0

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.2) :rocket:
