### ISSUE TITLE
Support for other bitmap font formats?

### ISSUE THREAD

**Issue by htdag** [jimp-dev/jimp#1009]
Hi,

[msdf-atlas-gen](https://github.com/Chlumsky/msdf-atlas-gen) is a new tool that supports many types of atlases:
Soft mark (like bmfont), MSDF (Scalability).
But currently this tool does not support exporting in standard bmfont format.

Hope jimp (plugin-print?) can add support for this.

**Comment by hipstersmoothie** [comment]
Merging into  #1170
