### ISSUE TITLE
@babel/runtime should be a dev dependency

### ISSUE THREAD

**Issue by Richienb** [jimp-dev/jimp#1013]
Every package in this monorepo specifies `@babel/runtime` as a `dependency`:

https://github.com/oliver-moran/jimp/blob/53ff9d1266207f7f674233f465ec358274510511/packages/jimp/package.json#L60-L61

However, this is a redundant package that is never used in the production code. It should be moved to the `devDependencies` section.

**Comment by lephuongbac** [comment]
The current package size is 21MB, it is too big for my small project.

**Comment by hipstersmoothie** [comment]
PRs welcome :D
