### ISSUE TITLE
How to scale PNG without anti-aliasing?

### ISSUE THREAD

**Issue by Arcanorum** [jimp-dev/jimp#1017]
**Is your feature request related to a problem? Please describe.**
I need to be able to scale some pixel art without it getting mangled.

Scaling by x4 currently anti-aliases all images.

Is there a nearest-neighbour scaling option?

![image](https://user-images.githubusercontent.com/9785268/120127565-98b35e80-c1b7-11eb-8607-3620428a4f81.png)

**Comment by Coreusa** [comment]
Another example (uses scale 2x and crop)

![Introductory gameplay-39980a739ee1a71](https://user-images.githubusercontent.com/706874/154851085-6e711b75-abfb-4ae1-902e-99b400af5040.png)

![header](https://user-images.githubusercontent.com/706874/154851087-21a288d7-48de-42fe-9f74-bbd82cae757d.png)

**Comment by Coreusa** [comment]
Figured it out. You have to use the Nearest Neighbour resize option.

```
await j.read('path/to/image.png')
  .then(res => {
    console.dir('Creating image.');
    return res
      .autocrop()
      .scale(2, Jimp.RESIZE_NEAREST_NEIGHBOR)
      .cover(1000, 350)
      .write('path/to/output-image.png')
  })
  .catch(e => {
    console.dir('Error occurred while creating the image.');
    console.dir(e
  })
```

## Here's a result without
![header-not-nearest](https://user-images.githubusercontent.com/706874/155335396-0f2f1170-42a1-4249-88c3-5a0d1d627a26.png)
);

## And then the same using the code above

![header-nearest](https://user-images.githubusercontent.com/706874/155335463-133e1546-e5bb-4960-9da5-7eb7e62a241c.png)

[More in the docs here](https://github.com/oliver-moran/jimp/tree/master/packages/jimp#resize-modes).
