### ISSUE TITLE
Colors messed up when writing png

### ISSUE THREAD

**Issue by kipcansheep** [jimp-dev/jimp#1022]
```
var jimg = new Jimp(128,128, 0x0);
const makeImage = () => {
  jimg.write('test.bmp');
  jimg.write('test.png');
  jimg.write('test.jpg');
}

makeImage();

```

The above code produces a black square, expected behavior, for both bmp and jpg. However it produces a transparent square for png. This is on an M1 mac.

**Comment by tgrajewski** [comment]
Seems to work as expected. You specified background color to be 0, which includes 0 opacity. To obtain black non-transparent square do 
```javascript
var jimg = new Jimp(128,128, 0x000000ff);
...
```
