### ISSUE TITLE
How to convert a hex code to HSL values?

### ISSUE THREAD

**Issue by sbr2567** [jimp-dev/jimp#1033]
Hi,

I'm able to convert a hex code to rgb values, this is what I used to convert hex to rgb. 

```
Jimp.intToRGBA(hex)
```

But how can I convert a hex code to HSL?
I want this to be able to analyse the color of an image.

Thanks.

**Comment by hipstersmoothie** [comment]
I would suggest using some other library to convert colors. jimp manipulates images, there are far better color converters. I'll probably remove that method to align with that
