### ISSUE TITLE
File name after conversion

### ISSUE THREAD

**Issue by elvispdosreis** [jimp-dev/jimp#1036]
I'm converting an image but I'm losing some properties like the filename, it's changed to "blob"

**Comment by dheimoz** [comment]
hey @elvispdosreis. As far as I am concerned, a blob is also a file. You should have properties.
You could "console.log" that blob and find the filename.

**Comment by elvispdosreis** [comment]
attached screen, it would be able to preserve the name

![image](https://user-images.githubusercontent.com/15267623/127868654-53bc3003-6d20-436a-9302-2465dd9ee9e1.png)

**Comment by elvispdosreis** [comment]
I managed to solve it by passing the third argument to uploadFormData.append
```
const uploadFormData = new FormData();
const name = file.name;
file = await readAndCompressImage(file, config);
uploadFormData.append('file' + item, file, name);
```
