### ISSUE TITLE
Wanted convolution edgeHandling example

### ISSUE THREAD

**Issue by mikakaraila** [jimp-dev/jimp#1037]
# Expected Behavior
How to use convolution function optional parameters like edgeHandling.

# Current Behavior
No clear or working example.

# Failure Information (for bugs)
TypeScript interface seems to need string, but Jimp.EDGE_WRAP etc. are defined as numbers.
Convolution code itself expects function as callback.

## Steps to Reproduce

- Jimp Version: 0.16.1
- Operating System: Windows 10
- Node version: nodev12.16.2

**Comment by kevinforrestconnors** [comment]
https://github.com/oliver-moran/jimp/blob/53ff9d1266207f7f674233f465ec358274510511/packages/plugin-color/test/convolution.test.js#L95

It expects a number, but the type is defined as string.

**Comment by kevinforrestconnors** [comment]
@mikakaraila to fix, you can cast it to a string.  But this could be fixed..

**Comment by hipstersmoothie** [comment]
The docs have been updated to be clearer https://github.com/jimp-dev/jimp/tree/master/packages/plugin-color#convolution
