### ISSUE TITLE
document image property access

### ISSUE THREAD

**Issue by tomprogers** [jimp-dev/jimp#1047]
Jimp can modify an image in a lot of ways, but the documentation doesn't explain how a person can access the image's current properties. Like reading its _current_ width or height.

Expand the API documentation to cover all the members of the object returned by `Jimp.read(...)`.

The only alternative is to traipse through all of the jimp source code. That should not be necessary.

**Comment by hipstersmoothie** [comment]
Would either of you like to update the docs to make that easier to discover?

**Comment by hipstersmoothie** [comment]
These values are in `image.bitmap.height` and `image.bitmap.width`. The new docs site makes this a little more discoverable I think. If it doesn't feel free to make a PR!
