### ISSUE TITLE
When I import Jimp I have console log: "I'm `fs` modules"

### ISSUE THREAD

**Issue by b01010110** [jimp-dev/jimp#1055]
# Expected Behavior

without any console logs

# Current Behavior

 console log: "I'm `fs` modules"

# Failure Information (for bugs)

.

## Steps to Reproduce

import Jimp from 'jimp'

**Screenshots**
![image](https://user-images.githubusercontent.com/79957072/146620776-243da67a-da0d-4666-b1d8-985177f05104.png)

## Context

- Jimp Version: ^0.16.1
- Operating System: Windows 10
- Node version: 16.13.0

**Comment by gouz7514** [comment]
Any progress about this issue?

**Comment by hipstersmoothie** [comment]
Is this still an issue?

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
