### ISSUE TITLE
getBase64Async returning stringified Promise

### ISSUE THREAD

**Issue by nolmsted** [jimp-dev/jimp#1056]
When using the getBase64Async function, a string like the following is returned 
`data:image/gif;base64,[object Promise]`

Looking at the source at this link ->
https://github.com/oliver-moran/jimp/blob/53ff9d1266207f7f674233f465ec358274510511/packages/core/src/index.js#L595

I'm guessing that the getBase64Async function is still calling the synchronous getBuffer()  rather than the async version. I was able to work around the issue with the following 

`image.getBufferAsync(image.getMIME()).then(data => {
       src = 'data:' + image.getMIME() + ';base64,' + data.toString('base64');`

**Comment by rdobda-gaia** [comment]
After upgrading to node 16, getBufferAsync is timing out on large files. I tried switching to getBase64Async then building a buffer from that result and it mostly worked until i hit this issue, which oddly only happened in some cases and not in others. If the solution is to go back to getBufferAsync then it's an infinite loop of problems.

**Comment by hipstersmoothie** [comment]
@nolmsted would you mind submitting a fix for this?

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
