### ISSUE TITLE
`getBufferAsync()` throws a string instead of an Error

### ISSUE THREAD

**Issue by nopeless** [jimp-dev/jimp#1057]
# Expected Behavior
```js
    Jimp.read(v)
      .then(lenna => lenna.resize(2000, Jimp.AUTO).getBufferAsync(`png`))
      .catch(e => {
        console.log(`type of e`, typeof e);
        throw e;
      })
```

Should log `object`

# Current Behavior

logs `string`

# Failure Information (for bugs)

## Steps to Reproduce

Here is a minimal reproducible example 

```js
import Jimp from "jimp";

Jimp.read(`response.png`)
  .then(lenna => lenna.resize(2000, Jimp.AUTO).getBufferAsync(`png`))
  .catch(e => {
    console.log(`type of e should be object`, typeof e);
    console.log(`e should be an instance of Error`, e instanceof Error);
  });
```

## Context

- Jimp Version: 0.16.1
- Operating System: windows 10
- Node version: 16.13.1

I am reporting this error because this broke my error catching express middleware.

![image](https://user-images.githubusercontent.com/38830903/148107541-86cb3c18-34ff-4ac0-831c-48a909f1988f.png)

Before the fix

Fixing by doing

```js
      .catch(e => {
        console.log(`type of e`, typeof e);
        throw new Error(e);
      })
```

After the fix

![image](https://user-images.githubusercontent.com/38830903/148107621-0eb97aef-d09e-457e-adc5-cceb3c8ca3ee.png)

Hope to see this fixed soon 👍

**Comment by nopeless** [comment]
bump

**Comment by intradeus** [comment]
`'png'` written like this isn't a MIME type ! 
Replace ``` .getBufferAsync(`png`)``` with  ```.getBufferAsync(Jimp.MIME_PNG)``` instead

**Comment by nopeless** [comment]
@intradeus @noahdeering can you please read. the issue states that the function is throwing a string not an error

**Comment by nopeless** [comment]
bump

**Comment by hipstersmoothie** [comment]
If anyone wants to submit a PR for this issue the fix should be easy. Willing to help merge and release!

**Comment by nopeless** [comment]
@hipstersmoothie #1138
