### ISSUE TITLE
pHash function not exposed on Jimp class

### ISSUE THREAD

**Issue by dlkulp** [jimp-dev/jimp#1058]
# Expected Behavior

After loading an image, `image.pHash()` should be exposed (per the documentation)

# Current Behavior

`.pHash()` has not been exposed and throws a type error.

# Failure Information (for bugs)

TypeError: image1.pHash is not a function

## Steps to Reproduce

```
async function compare() {
    const image1 = await Jimp.read("path/to/image1.jpg");
    image1.pHash();
}
```

## Context

Trying to save a pHash and compare against multiple additional images using `image2.distanceFromHash(image1.pHash())`

- Jimp Version: 0.16.1
- Operating System: Windows 10 build 19044.1415
- Node version: v14.17.4

## Failure Logs

(node:15180) UnhandledPromiseRejectionWarning: TypeError: image1.pHash is not a function
    at C:\Users\user\Documents\coding projects\test\jimptest.js:61:43
    at step (C:\Users\user\Documents\coding projects\test\jimptest.js:33:23)
    at Object.next (C:\Users\user\Documents\coding projects\test\jimptest.js:14:53)
    at fulfilled (C:\Users\user\Documents\coding projects\test\jimptest.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async 
function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nopeless** [comment]
I can't replicate this 🤔

**Comment by hipstersmoothie** [comment]
fixed
