### ISSUE TITLE
uncatchable error calling loadFont - crashes node 16 application

### ISSUE THREAD

**Issue by Steve-Mcl** [jimp-dev/jimp#1064]
# Expected Behavior

`const f = await Jimp.loadFont(fontFile);` 

should be catchable

If I add a catch handler, the error becomes catchable...

```js
            loadPages(_this, _path["default"].dirname(file), font.pages).then(function (pages) {
              cb(null, {
                chars: chars,
                kernings: kernings,
                pages: pages,
                common: font.common,
                info: font.info
              });
            })
            .catch(function(err) { //ADD CATCH HANDLER
              cb(err, null);
            });
```

# Current Behavior
When executing `const f = await Jimp.loadFont(fontFile);`, if the associated `xxxxx_0.png` is not found, `loadPages` promise in plugin-print index.js ([code permalink](https://github.com/oliver-moran/jimp/blob/53ff9d1266207f7f674233f465ec358274510511/packages/plugin-print/src/index.js#L196)) throws an exceptions but since the promise has no `.catch()` handler, nodejs 16 application halts

# Failure Information (for bugs)

## Steps to Reproduce

Try loading an `fnt` file without the associated png being present alongside the `fnt` file. 

## Context

- Jimp Version: 0.16.1
- Operating System: Windows 10
- Node version: v16.13.2

**Comment by hipstersmoothie** [comment]
@Steve-Mcl Could you submit a pr?

**Comment by hipstersmoothie** [comment]
I don't think this is an issue anymore in v1. If it is feel free to open a new issue
