### ISSUE TITLE
Error: certificate has expired: code: 'CERT_HAS_EXPIRED', methodName: 'constructor'

### ISSUE THREAD

**Issue by orestcodecare** [jimp-dev/jimp#1066]
# Failure Information

I'm using an electron to build a desktop application, and I need to convert the image. To do this, I decided to use your library.
I have code that loads the image and performs the conversion.
```
await Jimp.read({ imageUrl })
    .then((image) => {
      const white = 0xffffffff;
      return image
        .background(white)
        .resize(140, Jimp.AUTO)
        .greyscale()
        .contrast(1)
        .writeAsync(pathToImageFile);
    })
    .catch((err) => {
      console.error(err);
    });
```
However, depending on the type of build, I get a different result.
When I run a project in development mode or build it in staging mode, I get an error from this module, which is described below.
However, there is no such error in the production mode, and everything works fine.

# Attempts to solve

Tried to use information from your README and add headers to the query to avoid this behavior.
```
await Jimp.read({ url: imageUrl, headers: { rejectUnauthorized: false } })
```
However, this decision did not help and still there is an error.

Helped option with adding an environment variable that will ignore the following errors: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` however, this is a bad decision and I would not like to use it even for a staging build

## Steps to Reproduce

1. Create base electron application
2. Add function which will convert the image
3. Run app in development and production mode
4. In development mode you will see described error
5. In production mode function will work fine

## Context

- Jimp Version: "^0.16.1"
- Operating System: Windows 10, macOS Big Sur, Ubuntu 16.04
- Node version: v12.18.3
- ElectronJS version: "^11.5.0",
- ReactJS version: "^17.0.1"

## Failure Logs
```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'CERT_HAS_EXPIRED',
  methodName: 'constructor'
}
```

**Comment by hipstersmoothie** [comment]
I'm not sure this has anything to do with jimp? to me it looks like it's something in electron. Could you provide a reproduction repo? And since you're so close to the issue if you want to submit a PR I can help review and merge
