### ISSUE TITLE
Incomplete dependencies for types

### ISSUE THREAD

**Issue by pauldraper** [jimp-dev/jimp#1068]
# Expected Behavior

Packages to correctly state their dependencies.

For example:

* @jimp/bmp depends on @jimp/core
* @jimp/plugin-blit depends on @jimp/core.

# Current Behavior

* @jimp/bmp does not depend on @jimp/core
* @jimp/plugin-blit does not depend on @jimp/core

# Failure Information (for bugs)

This is causing TypeScript errors, depending on how the packages are linked.

Note that I don't believe these packages have runtime dependencies, but they do have *type* dependencies in the TS declarations.

## Steps to Reproduce

**Screenshots**

## Context

- Jimp Version:
- Operating System:
- Node version:

**Comment by hipstersmoothie** [comment]
@pauldraper Would you mind submitting a PR to fix this?

**Comment by hipstersmoothie** [comment]
I think all of these have been fixed now
