### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by adamsar** [jimp-dev/jimp#1079]
There seems to be a flood of unmerged PRs, no action on behalf of the owner for over a year, and the last release was two years ago. Is there an actual currently developed fork of this somewhere? It's a shame to lose a valuable alternative to sharp.

**Comment by Cormanz** [comment]
I would hope not, I still use jimp often.

**Comment by adamsar** [comment]
Looks to be the case unfortunately

**Comment by djaffer** [comment]
same I am stuck on upgrading to webpack 5 as well.

**Comment by arackaf** [comment]
I remember the author being extremely strapped for time, and being eager for new contributors. 

Hopefully someone can come forward to help keep this project moving forward. I absolutely love it. Extremely valuable alternative to Sharp.

**Comment by arackaf** [comment]
Just tossing this out there.  @oliver-moran would you be willing to start a Kickstarter, to try to raise some money to put you back to work on this project? 

I absolutely love Jimp, and I'd personally be willing to kick in some money to try to keep it moving forward.

**Comment by adamsar** [comment]
I'd donate to the cause as well. Maybe even help out with some code here or there. Although I don't think @oliver-moran is around Github anymore. Maybe we should consider doing a fork sooner or later.

**Comment by arackaf** [comment]
Hey all - one small update. I pinged Oliver (publicly) and this was his response, so if anyone is interested in being a contributor, sound off here, and he might add you. (I'd love to help but I know absolutely nothing about this project - I just adore being able to resize images in a Lambda function without pulling in huge binaries, like with Sharp)

<img width="597" alt="image" src="https://user-images.githubusercontent.com/11261266/164066971-e9596311-9213-4ff0-a9fc-774f2117b0cd.png">

**Comment by oliver-moran** [comment]
Hey, everyone. Thanks for opening this thread – and apologies I haven't been able to keep up with the work here.

Adam, I note your response above, but if it's OK with you could I lean on you to guide me as to what the community needs me to do to get things unblocked?

**Comment by arackaf** [comment]
@oliver-moran basically find someone you trust to drive the project forward, and grant them commit access to the project, and npm access to cut new versions.

A year or two ago you added me as a contributor, but I haven't been able to help much since I .... don't really know anything about image manipulation code. At all. LOL. I basically helped get some trivial PRs out. 

If we have any volunteers who are able and willing to try to maintain this project, sound off

**Comment by shtse8** [comment]
how is this now? are we going forward?

**Comment by demiankatz** [comment]
I see that v0.16.2 was released a couple of months ago, so the project clearly isn't entirely dead. Is this issue still needed?

**Comment by hipstersmoothie** [comment]
Hey @oliver-moran I've sent you a message on twitter on how to move forward with maintenance on jimp. In short:

We need to move the repo from under @oliver-moran's account to a shared org to make collaboration easier.

For that I've made https://github.com/jimp-dev

---

After a little break I'm happy to facilitate maintenance on the project. I'm also willing to help new maintainers hop on board. I myself do not plan on adding too much though.

**Comment by arackaf** [comment]
@hipstersmoothie - don't forget the npm keys, so others can cut releases. That's the key piece. Ya'll could just fork the repo anywhere you want, but you wouldn't be able to publish.

**Comment by hipstersmoothie** [comment]
I’m a owner of the nom package 👍🏼

**Comment by hipstersmoothie** [comment]
And now it's in the org 🎉 Going to close out this issue and some other and put out a new call for maintainers

**Comment by arackaf** [comment]
@hipstersmoothie ah! So sorry to tell you things you already knew.

Stoked to see this project moving forward again. Thank you so much for the work you're putting in!

**Comment by hipstersmoothie** [comment]
https://github.com/jimp-dev/jimp/issues/1128
