### ISSUE TITLE
how to do with the offSet for image?

### ISSUE THREAD

**Issue by exe19890522** [jimp-dev/jimp#1097]
i splite a big.png to some small pngs like:s1.png s2.png.
a json file give the image's argumes like this:
"shape11001_11001.png": {
      "x": 1498,
      "y": 2,
      "w": 138,
      "h": 154,
      "offX": -9,
      "offY": 66,
      "sourceW": 800,
      "sourceH": 800
    }
it means the sprite in a full image is not ALIGN_CENTER,it must need have some offset in new image.
but i don't know how to get this.

**Comment by hipstersmoothie** [comment]
You want to use the `displace` function
