### ISSUE TITLE
Writing a GIF results in crash with unhelpful error

### ISSUE THREAD

**Issue by skeddles** [jimp-dev/jimp#1099]
# Expected Behavior

`writeAsync()` to save thumbnailImage to a file  at newPath.

should mention it only fails for my GIF file, not PNG

# Current Behavior

crashes when running the code. despite trying to catch() or try{}catch(e){} it, it still crashes my whole app, and doesn't write out an error that tells me what line number is causing it. But taking the line out stops it from crashing.

yes newPath is a string.

# Failure Information (for bugs)

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise
    at new NodeError (node:internal/errors:387:5)
    at _write (node:internal/streams/writable:314:13)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at WriteStream.<anonymous> (/home/skeddles/lospec-file-processing-server/node_modules/@jimp/core/dist/index.js:589:18)
    at WriteStream.emit (node:events:513:28)
    at WriteStream.emit (node:domain:489:12)
    at node:internal/fs/streams:75:16
    at FSReqCallback.oncomplete (node:fs:196:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
## Steps to Reproduce

```
const Jimp = require('jimp');

new Jimp(256, 256, async (err, thumbnailImage) => {
	await thumbnailImage.writeAsync('./df.png');
});

```
except doing this outside of my app doesn't cause the crash, so i have no idea what to do. 

same thing happens when i do this, it crashes with the same error 
```
				thumbnailImage.write(newPath, (err,other) =>{
					console.log(err,other)
				})
```

both create a 0B file with the newPath filename

## Context

- Jimp Version:0.16.1
- Operating System: w11
- Node version: 16.17

**Comment by skeddles** [comment]
Okay I finally solved my problem. The secret is that writeAsync and write cannot accept gif as a format. 

So I guess :

**Bug report:** Trying to write to a gif file crashes with a terribly unhelpful untracable error - it should throw an error saying its an invalid filetype instead

or

**Feature Suggestion:** allow saving as gif

**Comment by hipstersmoothie** [comment]
merging into #1000
