### ISSUE TITLE
rotate(90) should have resulting width===oldHeight and height===oldWidth

### ISSUE THREAD

**Issue by arnhrwd** [jimp-dev/jimp#1101]
# Expected Behavior

`rotate(90)` should have resulting `width===oldHeight` and `height===oldWidth`

# Current Behavior

`rotate(90)` provides a rotated image with incorrect dimensions. Code for the plugin indeed shows it does things like uni-laterally increase the resulting width and height to be an even number, etc.

I assume it is the same for `rotate(-90)`, `rotate(180)`, and `rotate(-180)`

Probably some special cases could be considered for fast rotate.

- Jimp Version: ^0.16.2
- Operating System: Ubuntu
- Node version: 18.10

**Comment by hipstersmoothie** [comment]
@arnhrwd would you mind submitting a PR with the changes you have in mind?

**Comment by black-turtle** [comment]
Hi  @hipstersmoothie @arnhrwd if you guys don't mind can I work on this? as this is pending for some time.

I am thinking of using Matrix rotation, if rotate angle is multiple of 90 degrees.

I already have a workable solution. If it seems good I will create a PR.

If you want to check the code before PR, please check from [here](https://github.com/black-turtle/jimp/blob/issue-1101-fix/packages/plugin-rotate/src/index.js#L3-L91)

Thanks!

**Comment by hipstersmoothie** [comment]
If this works and the tests pass (and it solves the issue) I would love a PR!
