### ISSUE TITLE
measureText doesn't work on Autocode?

### ISSUE THREAD

**Issue by JaverHumberto** [jimp-dev/jimp#1106]
# Expected Behavior

I hope tha using measureText(font, text) function it returns the width of text in pixels

# Current Behavior

But i got this error message:
"error": {
    "message": "Cannot read property 'a' of undefined"
     ...}

where 'a' is the first character for the "text" string

# Failure Information (for bugs)

I'm not sure if this is becouse of the java version i'm using is that provided by autocode platform (https://autocode.com/)

Thanks for your help

**Comment by hipstersmoothie** [comment]
I'm not sure what this is. If you have a reproduction of an issue feel free to open another!
