### ISSUE TITLE
Image Manipulation Methods and getting information

### ISSUE THREAD

**Issue by bacloud23** [jimp-dev/jimp#1107]
Hi, Thanks a lot for making Jimp !

Image manipulation seems great with so many features, however, is there an API to get these information ? 
Like brightness, contrast, sharpness ?

I guess (I'm no image expert) that if you do image manipulation you have some valuable insights on the original data somewhere in the processing.

**Comment by hipstersmoothie** [comment]
that's not something we could add. jimp works by "decoding" images into bit maps. The manipulation function manipulate that bitmap so nothing is stored. That's why ordering function differently gives different effects!
