### ISSUE TITLE
word wrap on big strings

### ISSUE THREAD

**Issue by caamillo-athomos** [jimp-dev/jimp#1118]
# Expected Behavior
The string breaks at maxWidth

# Current Behavior
If I don't put whitespaces, it wont break at the maxWidth and it glitches out

# Failure Information (for bugs)

## Steps to Reproduce
I just printed text to img with maxWidth and tried to text a big string

**Screenshots**
![scarpe2](https://user-images.githubusercontent.com/119430144/210847352-629f9509-4404-44cf-a30b-d9d3caf2ec46.jpg)

## Context

- Jimp Version: 0.16.2
- Operating System: macOS Ventura 13.1
- Node version: 16.15.0

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.2) :rocket:
