### ISSUE TITLE
Same hash for different png images

### ISSUE THREAD

**Issue by rambonette** [jimp-dev/jimp#1119]
@teramotodaiki did you manage to find a workaround for this issue?

I'm experiencing the same issue with two completely different .png images, still the hash() function is returning the same "80000000000" hash.

I tried converting the two images to .jpg but obtained the same results.

```
Jimp.read('l3qn22kjlm.png', (err, res) => { console.log(res.hash())} );
Jimp.read('lcjb3u6c27.png', (err, res) => { console.log(res.hash())} );

//output
80000000000
80000000000
```

I'm currently using jimp package without any issues except for this one, so I'm guessing it has something to do with these specific  images:

![l3qn22kjlm](https://user-images.githubusercontent.com/7011942/211332074-58cd3e0e-5872-49f2-95b3-b587a0793456.png)

![lcjb3u6c27](https://user-images.githubusercontent.com/7011942/211332162-018edc9e-8ace-457e-a130-f9fa29860912.png)

Thanks in advance to all the kind souls willing to help :)

_Originally posted by @rambonette in https://github.com/oliver-moran/jimp/issues/338#issuecomment-1375712449_

**Comment by hipstersmoothie** [comment]
Merging into #338
