### ISSUE TITLE
Too many issues while using JIMP

### ISSUE THREAD

**Issue by Fomeistaken** [jimp-dev/jimp#1121]
I am trying to run JIMP in a browser using React.js and Node.js 18.13.0 and Jimp 0.16.2 (OS Windows 10, browser Opera GX)
When i start the code it returns the following error

`Compiled with problems:X

ERROR in ./node_modules/@jimp/core/es/index.js 29:33-46

Module not found: Error: Can't resolve 'fs' in '<Project Directory>\node_modules\@jimp\core\es'

ERROR in ./node_modules/@jimp/core/es/index.js 30:35-50

Module not found: Error: Can't resolve 'path' in '<Project Directory>\node_modules\@jimp\core\es'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

ERROR in ./node_modules/@jimp/plugin-print/es/index.js 10:35-50

Module not found: Error: Can't resolve 'path' in '<Project Directory>\node_modules\@jimp\plugin-print\es'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }`

**The error is shown when i import the module without even using it in the code**
`let Jimp = require('jimp');`
I also tried this
`import * as Jimp from 'jimp';`

**Comment by gundall** [comment]
Same issue here. I was using Vite to build my website, and due to the problems that Vite has with `require`, I switched to cra, and then it got worse.

In addition to what @Fomeistaken already tried, I also tried to install "fs" and "path" modules, but it did nothing.

**Comment by hipstersmoothie** [comment]
I just released a better browser build. If that doesn't fix your problem feel free to open another issue with a reproduction
