### ISSUE TITLE
Get karma browser tests running again

### ISSUE THREAD

**Issue by hipstersmoothie** [jimp-dev/jimp#1129]

**Comment by nopeless** [comment]
@hipstersmoothie on it

**Comment by hipstersmoothie** [comment]
Oh wait!

**Comment by hipstersmoothie** [comment]
Before you do this I think you should look into using this project

https://twitter.com/HipsterSmoothie/status/1622298963486572544

It seems a bit newer and support using playwright which would be really nice to use.

**Comment by hipstersmoothie** [comment]
It might also be easier to get playwright running on CI than karma

**Comment by hipstersmoothie** [comment]
we use vitest browser mode now
