### ISSUE TITLE
Remove intToRGBA

### ISSUE THREAD

**Issue by hipstersmoothie** [jimp-dev/jimp#1146]
jimp isn't a color converter, our public api should expose anything like that.

**Comment by nopeless** [comment]
I agree. It should at least be a separate module

We are polluting the global Jimp namespace too much imo

**Comment by hipstersmoothie** [comment]
Yeah exactly. There are also countless better npm color packages. Jimp does mainly 3 things:

1. decode images into bitmaps
2. manipulate those bitmaps
3. encode those bitmaps into new images

I think we should make jimp great at those things and let other packages handle the rest
