### ISSUE TITLE
A lot ofNPM Publishes

### ISSUE THREAD

**Issue by mastrzyz** [jimp-dev/jimp#1177]
@hipstersmoothie  we noticed there are a lot of npm publishes for this package:
![image](https://user-images.githubusercontent.com/37447884/217042516-98aadf3a-d938-4d3a-a445-635f5b2fb25e.png)

Is this by design? not sure every commit is meant to publish here.

**Comment by hipstersmoothie** [comment]
That's intended. Those are all test versions for PRs
