### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by sergeu90** [jimp-dev/jimp#1178]
# Expected Behavior

Without error.

# Current Behavior

![image](https://user-images.githubusercontent.com/7217517/217054586-f079117d-a30d-4e48-bd82-b815990a5ce1.png)

# Failure Information (for bugs)

After update to  0.22.1 error appears.

## Steps to Reproduce

1. Update to 0.22.1 
2. import Jimp from 'jimp/browser/lib/jimp';

## Context

- Jimp Version: 0.22.1
- Operating System: mac os.
- Node version: 14.20.0

**Comment by hipstersmoothie** [comment]
Could you provide a simple repro

**Comment by marvinruder** [comment]
Similar issue for me, using the browser version as well. Error message reads `undefined is not an object (evaluating '(k.env.__TESTING_MKDIRP_NODE_VERSION__ || k.version).replace')`.

Also reproducable by simply opening [`example2.html`](https://github.com/jimp-dev/jimp/blob/main/packages/jimp/browser/examples/example2.html) in a browser.

**Comment by sergeu90** [comment]
@hipstersmoothie  after updated to last i have another issue 
![image](https://user-images.githubusercontent.com/7217517/217367090-48bd6d2d-976d-4b7b-af5d-be31e7e8d7ea.png)

**Comment by marvinruder** [comment]
Looks like the “… is undefined / not a function” issue from #1194 to me.

@sergeu90 Are you still using the `browser/lib/jimp.js` version as mentioned above? I can reproduce the issue for the `"jimp"` or `"jimp/es"` import, but not the browser version.

**Comment by sergeu90** [comment]
@marvinruder Yes. I import with browser/lib/jimp.js

**Comment by marvinruder** [comment]
Okay, this is odd, Browser import always still worked fine for me. @sergeu90 Can you share an MWE to reproduce the issue with `browser/lib/jimp.js`, perhaps in a small repository?

**Comment by simonandywilson** [comment]
I'm also getting the error `TypeError: Cannot read properties of undefined (reading 'replace')` when importing `v0.22.7` of Jimp
