### ISSUE TITLE
V1 Remove fetch polyfill

### ISSUE THREAD

**Issue by danielholmes** [jimp-dev/jimp#1179]
We recently introduced a fetch polyfill to avoid breaking a bunch of projects. This should be removed in a major version (i.e. V1) and documentation added about requiring fetch for the `loadFromURL` behaviour.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
