### ISSUE TITLE
Jimp not working on React Native 

### ISSUE THREAD

**Issue by Njinou** [jimp-dev/jimp#1191]
# Expected Behavior
I expect the library to work properly and the image to be shrink in size for a better User Experience.

# Current Behavior
It crashes with this error:  [TypeError: _$$_REQUIRE(_dependencyMap[9], "jimp").read is not a function. (In '_$$_REQUIRE(_dependencyMap[9], "jimp").read('https://media.geeksforgeeks.org/wp-content/uploads/20190328185307/gfg28.png')', '_$$_REQUIRE(_dependencyMap[9], "jimp").read' is undefined)]

# Failure Information (for bugs)

## Steps to Reproduce
yarn add Jimp on react-native vanilla
//import Jimp from "jimp";
               Or 
var Jimp = require("jimp");

 try{ 
         Jimp.read
                ('https://media.geeksforgeeks.org/wp-content/uploads/20190328185307/gfg28.png').then (image => console.log("Images",image))
                .catch(e => console.log("first casth ",e))
        }
        catch(e){
            console.log("this is the error ",e);
        }

**Screenshots**

## Context

- Jimp Version:
- Operating System:
- Node version:
![Uploading Screen Shot 2023-02-07 at 2.55.31 AM.png…]()<img width="791" alt="Screen Shot 2023-02-07 at 3 01 07 AM" src="https://user-images.githubusercontent.com/33528310/217199424-3041223d-7434-4352-bd72-0a41cf9b9cf6.png">## Failure Logs

**Comment by marvinruder** [comment]
I am not too familiar with React Native, but its Javascript engine might require the browser version of Jimp. This is how I got it running in (classic) React:

```
await import("jimp/browser/lib/jimp.js"); // This statement loads the browser version of Jimp and makes it available as the global variable `window.Jimp`.
const { Jimp } = window as typeof window & { Jimp: any }; // any can probably be replaced with something else from the Jimp package
```

**Comment by marvinruder** [comment]
@Njinou Can you share your Typescript configuration with us? I was able to reproduce the issue in a setup with `allowSyntheticDefaultImports` set to `true`, but without `esModuleInterop`. After replacing `allowSyntheticDefaultImports` with `esModuleInterop`, Jimp works fine for me.

**Comment by Njinou** [comment]
Oh i have a nodejs React Native project not a typescript one so on this
particular project i do not have the tsconfig.json file
Not aure if it does matter.
 Thanks

**Comment by marvinruder** [comment]
Okay, I tried reproducing the issue in plain Javascript, but was unsuccessful so far. Perhaps you can provide a small repository setup which reproduces the issue?

**Comment by marvinruder** [comment]
@hipstersmoothie Can you have a look at my MWE repo [marvinruder/jimp-react](https://github.com/marvinruder/jimp-react)?

It appears that over the years many issues were found when attempting to use Jimp in frontend tools like React (Native) (see this one and also #1091, #761), so maybe we can use a setup like mine to find and fix them one by one? Perhaps the more general goal of getting Jimp running in frontend tools should be tracked in a separate issue? Let me know what you think!

**Comment by hipstersmoothie** [comment]
Yeah let's do that! 

I just invited you to the org. Maybe you could transfer the repo there and we could use it to test issues like this in the future. 

I think that you should created another issue that tracks this like you said and merge all of these other issues into it

**Comment by hipstersmoothie** [comment]
Once you access the invite I'll also give you triage access to this repo

**Comment by marvinruder** [comment]
Thanks for reporting this bug, @Njinou! We are currently investigating several issues with Jimp in frontend tools such as React [Native], and will consolidate the discussion there. We will therefore close this issue as duplicate, but continue to work on a fix. You can follow the progress on that in #1194.

**Comment by Njinou** [comment]
@marvinruder  Please let me know if I can be of any help to speed up  the fix 
Thanks
