### ISSUE TITLE
Migrate the repository to use Yarn Berry

### ISSUE THREAD

**Issue by crutchcorn** [jimp-dev/jimp#1196]
Currently, we're using Yarn 1, which the core Yarn team has stated they do not plan to continue to maintain.

Instead, we should migrate to using Yarn Berry (Yarn 3) or another package manager.

If we do go with Yarn Berry, they often suggest using [Yarn Plug'N'Play (PNP)](https://yarnpkg.com/features/pnp/) and commit the `node_modules` cache into Git versioning. I dislike this strategy, however, and often opt to use `nodeLinker: node-modules` instead, which mirrors the behavior of Yarn 1 and NPM much more closely.

An example of this setup is as follows:

https://github.com/crutchcorn/react-native-monorepo-example/blob/main/.yarnrc.yml

**Comment by hipstersmoothie** [comment]
I did pnpm instead
