### ISSUE TITLE
convert png to gif failed

### ISSUE THREAD

**Issue by YAKUNAMAKAKA** [jimp-dev/jimp#1200]
# right gif
![Group 35](https://user-images.githubusercontent.com/75433853/218267165-cead0f1a-4ecf-4cba-86b4-2e19a06c47e2.png)

# the black and wrong gif
![image](https://user-images.githubusercontent.com/75433853/218267169-a11ae228-f0ca-4ccb-bd2f-dcf5ebafe4b2.png)

# i try to convert png to gif.but get wrong gif .

## use this case in react
import Jimp from 'jimp/browser/lib/jimp';
import React, { Component } from 'react';
import './index.less'
import test from 'assets/testJimp/test.png';
import exportButton from "@/assets/meme-maker/export-button.png";
interface Props {};
interface State {};

class MyComponent extends Component<Props, State> {
    processImage = async () => {
        try {
            const png = await Jimp.read(test);
            console.log(`PNG Image width: ${png.bitmap.width}, height: ${png.bitmap.height}`);
            const gif = new Jimp(png.bitmap.width, png.bitmap.height, (err, image) => {
                image.composite(png, 0, 0);
                console.log(`GIF Image width: ${image.bitmap.width}, height: ${image.bitmap.height}`);
            });

            const gifData = await gif.getBase64Async(Jimp.MIME_JPEG);
            const link = document.createElement('a');
            link.download = 'processed-image.gif';
            link.href = gifData;
            link.click();
        } catch (error) {
            console.error(error);
        }
    }

    render() {
        return (
            <div >
                <button onClick={this.processImage}>

                    <img src={test} width="100%" alt="export-button" />
                </button>
            </div>
        );
    }
}

export default MyComponent;

**Screenshots**

## Context

- Jimp Version:jimp@0.16.2
- Operating System:windows10
- Node version:17

**Comment by YAKUNAMAKAKA** [comment]
![test](https://user-images.githubusercontent.com/75433853/218266761-d4c2e3c9-d39b-4926-a950-52f8974418c5.gif)
i got this ...

**Comment by YAKUNAMAKAKA** [comment]
i have little exprience in programing...Maybe jimp couldn't convert png to gif?

**Comment by danielholmes** [comment]
@YAKUNAMAKAKA your problem if the ordering of when the operations are run. If you added another console log just before encoding:

```
try {
  const png = await Jimp.read(test);
  console.log(`PNG Image width: ${png.bitmap.width}, height: ${png.bitmap.height}`);
  const gif = new Jimp(png.bitmap.width, png.bitmap.height, (err, image) => {
    image.composite(png, 0, 0);
    console.log(`GIF Image width: ${image.bitmap.width}, height: ${image.bitmap.height}`);
  });
  console.log("Encoding");
  const gifData = await gif.getBase64Async(Jimp.MIME_JPEG);
  const link = document.createElement('a');
  link.download = 'processed-image.gif';
  link.href = gifData;
  link.click();
  // ...
```

You'll notice that the console logs will be ordered:

```
PNG Image...
Encoding...
GIF Image...
```

It's because of when the callback is fired. Note that `Jimp.read` takes all the same arguments as the constructor, so you can fix this by changing to:

```
//...
const png = await Jimp.read(test);
console.log(`PNG Image width: ${png.bitmap.width}, height: ${png.bitmap.height}`);
const gif = await Jimp.read(png.bitmap.width, png.bitmap.height);
gif.composite(png, 0, 0);
console.log(`GIF Image width: ${gif.bitmap.width}, height: ${gif.bitmap.height}`);
//...
```
