### ISSUE TITLE
Unintuitive design for plugin-rotate

### ISSUE THREAD

**Issue by Jiralite** [jimp-dev/jimp#1201]
# Expected Behavior

I expect to use the method without instantiation of any sort.

# Current Behavior

The current behaviour yields an unintuitive design that does not work in TypeScript.

# Failure Information (for bugs)

I found this earlier and decided to test this out. To be clear, I am using only this package and not other packages.

Upon running the following:

```JavaScript
import rotate from "@jimp/plugin-rotate";

console.log(rotate());
```

I expected this to call the method. However, this actually instantiates an object that contains a property which has the method. This... is not what I expected. This means in order to use this method, one would have to do `rotate().rotate(...)`.

This gets worse in TypeScript. With `"moduleResolution": "node16"` or later in your tsconfig.json, The definitions are wrong:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/33201955/218865650-ad0685a1-7ab2-446e-ab01-a75155880f87.png">

This results in a runtime error:

```xl
rotate.default().rotate();
              ^

TypeError: rotate.default is not a function
    at file:///Users/jiralite/Documents/Code/thatskyapplication/Caelus/sourceJS/14.js:46:27
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

Just a note, but wouldn't it also be intuitive to see the issue description first, then the steps to reproduce, expected behaviour, and then the current/actual behaviour?

## Steps to Reproduce

1. Run `npm install @jimp/plugin-rotate`
2. Use the following code in TypeScript:

```TypeScript
import rotate from "@jimp/plugin-rotate";

rotate.default().rotate(0); // No compile error, but fails.
```

## Context

- Jimp Version: @jimp/plugin-rotate@0.22.4
- Operating System: macOS Ventura 13.1
- Node version: 19.6.0
- TypeScript: 4.9.4

## Failure Logs

See above.

**Comment by hipstersmoothie** [comment]
This is not how you use plugins so I see why that might fail! You're not supposed to use plugins directly like that. They are meant for registering image types and manipulation functions on a jimp instance. Luckily this one is included by default!

Here are the docs for plugin usage
