### ISSUE TITLE
Bad quality (JPEG Compression) when saving PNG

### ISSUE THREAD

**Issue by super-ienien** [jimp-dev/jimp#121]
Hi,

I'm having some trouble with image quality on JIMP.
I just download some JPEGs and save them as PNGs : 

`Jimp.readAsync(url)
    .then(function (image)
    {
        return image.writeAsync("image.png")
    }
`

The quality of the PNG is bad comparing to the original JPEG. It's like I was saving it twice in JPEG. See the exemple here (you can see that additionnal JPEG artefacts are presents around the white letters in the PNG): 

ORIGINAL JPEG 
![cgajreywqaewbai](https://cloud.githubusercontent.com/assets/1185858/14543999/15c26a0a-0297-11e6-8705-7c81d06e4f44.jpg)

SAVED PNG
![image 1__media_cgajreywqaewbai](https://cloud.githubusercontent.com/assets/1185858/14543995/11f0950a-0297-11e6-8a3c-32a642d7d54f.png)

**Comment by oliver-moran** [comment]
These aren't methods from this library:

```
Jimp.readAsync(url) ... image.writeAsync ...
```

How are you calling them?

**Comment by super-ienien** [comment]
Sorry, i'm using promisification functionnality of bluebird. So readAsync ad writeAsync are the promisified version of read and write method from Jimp.

**Comment by oliver-moran** [comment]
I'm doing a release in a few days. That will have some fixes in it, could you check again then?

**Comment by super-ienien** [comment]
I don't have time to test it again but i think it's due to the pngjs package more than Jimp

**Comment by oliver-moran** [comment]
Yes, definitely to do with pngjs. I'll keep an eye on it and if there's improvement to that library I'll pull it in. Thanks for logging it.

**Comment by oliver-moran** [comment]
Tested again after updating pngjs. Issues still presents.

**Comment by oliver-moran** [comment]
Suspect same as this issue: https://github.com/oliver-moran/jimp/issues/121

**Comment by hipstersmoothie** [comment]
still an issue

**Comment by hipstersmoothie** [comment]
https://github.com/eugeneware/jpeg-js/issues/17

**Comment by hipstersmoothie** [comment]
If you want more accurate image codecs please use the WASM ones. The exact issue here is probably an issue with one of the default JS based codecs.
