### ISSUE TITLE
Jimp not woking in docker container

### ISSUE THREAD

**Issue by NiazMuhammad-gif** [jimp-dev/jimp#1219]
# Expected Behavior

Jimp should work in docker container

# Current Behavior

Jimp is not working correctly in docker container

**Comment by myyellowshoe** [comment]
I'm probably going use it in a docker container, could you give some more insight on whats going on? what error your getting?

**Comment by hipstersmoothie** [comment]
If there is an issue open to PRs that fix it! Jimp doesn't really on any native modules so it shouldn't really matter

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
