### ISSUE TITLE
How to support Chinese fonts when adding text?

### ISSUE THREAD

**Issue by 17602260250** [jimp-dev/jimp#1232]
How to support Chinese fonts when adding text?
How to modify font color?
Add Chinese Want to download font packs?
won't this be very friendly

**Comment by hipstersmoothie** [comment]
> How to support Chinese fonts when adding text?
you simply load a font that uses Chinese characters. here is a guide https://github.com/jimp-dev/jimp/issues/419#issuecomment-1687934829
