### ISSUE TITLE
browser build breaks in Vercel edge production

### ISSUE THREAD

**Issue by da7a90-backup** [jimp-dev/jimp#1238]
# Expected Behavior
expect the browser build to work in the edge runtime's production environment using `import * as _jimp from 'jimp'` workaround mentioned in #1194 also with `unstable_allowDynamic` enabled but it doesn’t seem to have any effect on it.

# Current Behavior
it works locally and in the preview staging environment but not in production 

# Failure Information (for bugs)
According to Nextjs docs Source Maps are disabled unless your provide a ` productionBrowserSourceMaps: true,` flag which I haven't tested yet. 

## Steps to Reproduce
use jimp in a vercel edge function locally and try to push to production via github actions.

## Context

- Jimp Version:^0.22.8
- Operating System: MacOS locally and Vercel Edge runtime in production  
- Node version: latest

## Failure Logs
```- warn node_modules/jimp/browser/lib/jimp.js (2:329112) @ Function
- warn Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Edge Runtime
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation```

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
