### ISSUE TITLE
Build failure due to bundle size. Advice on how to reduce please

### ISSUE THREAD

**Issue by DiegoMcDipster** [jimp-dev/jimp#1241]
# Expected Behavior
Build succeeds.
I saw on https://github.com/jimp-dev/jimp/issues/493#issuecomment-1416814742 that the recommendation is to use @jimp/custom.  But I have no idea how to use it for what I want to do.

I'm using jimp for cropping and merging and that's it. Here's my code:
```import _Jimp from "jimp";
const Jimp = typeof self !== "undefined" ? self.Jimp || _Jimp : _Jimp;

  async function mergeImages(image1: string, image2: string) {
    const jimpImage1 = await Jimp.read(image1);
    const jimpImage2 = await Jimp.read(image2);

    const mergedImage = new Jimp(
      jimpImage1.getWidth(),
      jimpImage1.getHeight() + jimpImage2.getHeight()
    );

    mergedImage.composite(jimpImage1, 0, 0);
    mergedImage.composite(jimpImage2, 0, jimpImage1.getHeight());

    return await mergedImage.getBase64Async("image/png");
  }

  const cropImage = async (image: string, isHeading: boolean) => {
    const y = isHeading ? 144 : 80;
    const croppedImage = await Jimp.read(image);

    croppedImage.crop(140, y, 940, 1400);

    return await croppedImage.getBase64Async("image/png");
  };
```
My question is how would I use @jimp/custom to achieve the same result?

# Current Behavior
I've a NextJs app on aws amplify and now that I added jimp, the build fails because the bundle > 200MB. 

# Failure Information (for bugs)
CustomerError: The size of the build output (258964904) exceeds the max allowed size of 230686720 bytes

## Steps to Reproduce
It's not an issue,  it's advice i need.

## Context
- Jimp Version: 0.22.8
- Operating System: Linux
- Node version: 18

## Failure Logs
CustomerError: The size of the build output (258964904) exceeds the max allowed size of 230686720 bytes

**Comment by hipstersmoothie** [comment]
http://jimp-dev.github.io/jimp/guides/custom-jimp/
