### ISSUE TITLE
Do you support vite?

### ISSUE THREAD

**Issue by suzhenghui-sky** [jimp-dev/jimp#1244]
# Expected Behavior

jimp.read should not be undefined
# Current Behavior

jimp.read is undefined

# Failure Information (for bugs)

import Jimp from 'jimp';
console.log(Jimp.read) // undefined
## Steps to Reproduce

**Screenshots**

## Context

- Jimp Version:  "^0.22.8",
- Operating System: window 10
- Node version: v18.16.0

**Comment by suzhenghui-sky** [comment]
![图片](https://github.com/jimp-dev/jimp/assets/48371536/d3e21edd-7e4d-40ff-b2b1-9c637e0dd98b)

**Comment by mustafaekim** [comment]
Is it possible to use Jimp with vite?

**Comment by suzhenghui-sky** [comment]
> 

I don't think so.

**Comment by suzhenghui-sky** [comment]
> Is it possible to use Jimp with vite?

I don't think so.

**Comment by JasonKwok8588** [comment]
are you use in web browser?
you can try :
import "jimp/browser/lib/jimp.js";
console.log(Jimp.read)

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:

**Comment by sergeushenecz** [comment]
How to use in web after release this package?

**Comment by hipstersmoothie** [comment]
http://jimp-dev.github.io/jimp/guides/browser/

**Comment by sergeushenecz** [comment]
It doen't work in vite. I tried and use jimp/browser and jimp

**Comment by hipstersmoothie** [comment]
That stack trace seems odd. Could you share a minimal repro?

**Comment by hipstersmoothie** [comment]
So there was a problem with us not shipping the browser files. That's fixed in `1.1.3`.

Lookin into making the bundler experience more automatic

**Comment by sergeushenecz** [comment]
I noticed on prev version of library works 

`await Jimp.read(ctx.getImageData(0, 0, canvas.width, canvas.height));`

<img width="531" alt="image" src="https://github.com/user-attachments/assets/7ebf2025-3754-4f8b-b5e3-20a228d45f01">


but now i see error

**Comment by hipstersmoothie** [comment]
what previous version?

**Comment by sergeushenecz** [comment]
"jimp": "0.22.12",

**Comment by hipstersmoothie** [comment]
It looks like in v1 you would call `fromBitmap` instead of `fromBuffer`

**Comment by sergeushenecz** [comment]
@hipstersmoothie  I updated to 1.2.0 version and use 

`import Jimp from 'jimp';`

but see error 
`node_modules/.vite/deps/jimp.js?v=84fca0b0' does not provide an export named 'default'`

**Comment by hipstersmoothie** [comment]
That's cause Jimp has no default export anymore.

```js
import { Jimp } from 'jimp';
```

**Comment by sergeushenecz** [comment]
A lot of thanks for support

**Comment by hipstersmoothie** [comment]
no prob! added to migration guide http://jimp-dev.github.io/jimp/guides/migrate-to-v1/

**Comment by daveroberts** [comment]
As of version 1.6.1 you may get this error, but the root cause looks to be [this issue](https://github.com/jimp-dev/jimp/issues/1402)
