### ISSUE TITLE
Nimp link on read me directs to wrong website

### ISSUE THREAD

**Issue by mattrichmo** [jimp-dev/jimp#1253]
# Expected Behavior

 to go to the nimp pqge 

# Current Behavior

 it's currently redirecting to a fyp game 

# Failure Information (for bugs)

## Steps to Reproduce

**Screenshots**

## Context

- Jimp Version:
- Operating System:
- Node version:

## Failure Logs

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
