### ISSUE TITLE
.brightness() method does not affect brightness

### ISSUE THREAD

**Issue by Gabilabrebi** [jimp-dev/jimp#1273]
# Expected Behavior

.brightness() method should affect brightness

# Current Behavior

.brightness() method does not affect brightness but blend white with image everywhere

# Failure Information (for bugs)

See above

## Steps to Reproduce

1) Use .brightness(0.9) on an .jpg image to go near full brightness
2) Create image file with writeAsync()

**Screenshots**

1) Brightness 0.9 in JIMP (nearly full brightness)
![near_full_brightness_jimp](https://github.com/jimp-dev/jimp/assets/39853761/06b376eb-fbca-4c61-b5ad-89d7c11bea34)

2) Brightness 4 in CSS (nearly full brightness)
![near_full_brightness_real](https://github.com/jimp-dev/jimp/assets/39853761/4ca91e28-997d-4570-be65-7f4a7277a96d)

## Context

No special conditions

- Jimp Version: 0.22.10
- Operating System: Windows
- Node version: 21.5.0

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.2) :rocket:
