### ISSUE TITLE
Jimp.decoders is undefined in browser with webpack and typescript

### ISSUE THREAD

**Issue by smithbk** [jimp-dev/jimp#1276]
# Expected Behavior

I am expecting Jimp.decoders to be defined when running in a browser using webpack and typescript

# Current Behavior

Jimp.decoders (and other fields) is undefined

# Failure Information (for bugs)

An exception is thrown when trying to reference any field in Jimp.

## Steps to Reproduce

1. Unzip the attached jimp.zip 
[jimp.zip](https://github.com/jimp-dev/jimp/files/14228346/jimp.zip)
2. cd jimp
3. npm run debug
4. open browser to "http://localhost:4000".  View the browser console output (via inspect in Chrome) and you will see the log message with the value of "Jimp.decoders".

**Screenshots**

## Context

- Jimp Version: 0.22.10
- Operating System: macOS Ventura 13.6.3 
- Node version: 16.20.2

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
