### ISSUE TITLE
zlib_bindings problem when used in Vite with Typescript

### ISSUE THREAD

**Issue by Dylan190774** [jimp-dev/jimp#1281]
# Expected Behavior

I expect no error messages when running the application

# Current Behavior

The application build goes well, but when the application starts I get the following error:

```
[vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/zlib/lib/zlib.js:1:25: ERROR: Could not resolve "./zlib_bindings"
    at failureErrorWithLog (C:\xampp\htdocs\testproject\node_modules\vite\node_modules\esbuild\lib\main.js:1651:15)
    at C:\xampp\htdocs\testproject\node_modules\vite\node_modules\esbuild\lib\main.js:1059:25
    at C:\xampp\htdocs\testproject\node_modules\vite\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Steps to Reproduce

I use Vite as builder (default in Quasar Framework).
In a Typescript file I use:

```
import Jimp from 'jimp';

///

Jimp.read(imagefile)
  .then((image) => {
    console.log(image);
});


```
I deleted entire `node_modules `folder and `yarn.lock` file and ran 'yarn' again.
Doesn't resolve the issue.

As a workaround I now use: 

`import 'jimp/browser/lib/jimp.js';`

With that the application runs ok, but Visual Studio Code then gives 2 Eslint warnings:

- Cannot find name 'Jimp'
- Parameter 'image' implicitly has an 'any' type

I don't know what kind of object 'image' should be. (I'm learning Typescript, and have some trouble understanding which types there are in a library like yours).

## Context

- Jimp Version:    latest version (in package.json it says '^0.22.12')
- Operating System: Windows 10
- Node version: v20.11.1

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.0.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.0.2) :rocket:
