### ISSUE TITLE
Cannot load fonts in Web Worker

### ISSUE THREAD

**Issue by av01d** [jimp-dev/jimp#1286]
I am confused... was issue #289 ever considered? Using fonts in a WebWorker (still) does not work.
Example worker:
```
importScripts('./jimp.js');

(async () => {

  const font = await Jimp.loadFont('fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt');

  self.addEventListener('message', e => {
    Jimp.read(e.data).then((img) => {
      img
      .print(font, 10, 10, "Hello World!")
      .getBase64(Jimp.AUTO, (err, src) => {
        if (err) throw err;
        self.postMessage(src);
      });
    });
  });

})();
```
The following error is thrown:
```
jimp.js:2 Uncaught (in promise) Error: error parsing font document is not defined
```
Using latest version of jimp (0.22.12)

_Originally posted by @av01d in https://github.com/jimp-dev/jimp/issues/289#issuecomment-2009614925_

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.5`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.5) :rocket:
