### ISSUE TITLE
Unable to install jimp library through npm bcz of vulnerabilities checks

### ISSUE THREAD

**Issue by RagaviMuthukrishnan** [jimp-dev/jimp#1289]
phin  <3.7.1 Severity: moderate phin may include sensitive headers in subsequent requests after redirect - https://github.com/advisories/GHSA-x565-32qp-m3vf fix available via npm audit fix --forceWill install jimp@0.3.11, which is a breaking change node_modules/phin load-bmfont  >=1.4.0 Depends on vulnerable versions of phin node_modules/load-bmfont @jimp/plugin-print  >=0.4.0 Depends on vulnerable versions of load-bmfont node_modules/@jimp/plugin-print @jimp/plugins  >=0.4.0 Depends on vulnerable versions of @jimp/plugin-print node_modules/@jimp/plugins jimp  >=0.4.0 Depends on vulnerable versions of @jimp/plugins node_modules/jimp

5 moderate severity vulnerabilities

- tried updated node version to latest which didn't help
- tried installing jimp lower version which didn't help
- Tried npm audit fix --force which didn't help

**Comment by RamK777-stack** [comment]
Related #1291

**Comment by CC52-dev** [comment]
@hipstersmoothie fix this

**Comment by hipstersmoothie** [comment]
library no longer uses phin in v1
