### ISSUE TITLE
Update phin version

### ISSUE THREAD

**Issue by RamK777-stack** [jimp-dev/jimp#1291]
When running yarn audit getting, I am already on latest version `0.22.12`

<img width="317" alt="image" src="https://github.com/jimp-dev/jimp/assets/69167444/d3ac907a-a25c-490d-b0e9-4f2b7a0ca178">

**Comment by carlosvf93** [comment]
I have the same problem :(

**Comment by carlosvf93** [comment]
Any expected date for the update?

**Comment by kennyma-eplus** [comment]
I have the same same problem ~

**Comment by carlosvf93** [comment]
> I have the same same problem ~

Finally I moved to another library, this one looks like is not being maintained.

**Comment by kennyma-eplus** [comment]
> > I have the same same problem ~
> 
> Finally I moved to another library, this one looks like is not being maintained.

Any suggested library ?

**Comment by carlosvf93** [comment]
> > > I have the same same problem ~
> > 
> > 
> > Finally I moved to another library, this one looks like is not being maintained.
> 
> Any suggested library ?

yes, I'm using `sharp`, is very similar: https://github.com/lovell/sharp

**Comment by kennyma-eplus** [comment]
> > > > I have the same same problem ~
> > > 
> > > 
> > > Finally I moved to another library, this one looks like is not being maintained.
> > 
> > 
> > Any suggested library ?
> 
> yes, I'm using `sharp`, is very similar: https://github.com/lovell/sharp The vulnerabilities are fixed in his last version and looks like a secure/maintained library.

yes, i remember I looked `sharp` before..
it stop me at `Could not load the \"sharp\" module using the linux-arm64 runtime`
:(

**Comment by jeffreycastro** [comment]
@kennyma-eplus for the sharp issue i fixed it by doing the ff for my serverless lambda
1. in package.json i added under "scripts": `"force-install-linux": "npm install --force @img/sharp-linux-x64",` (for you might need to change x64 to arm64)
2. in my deploy pipeline i run `npm run force-install-linux` before running `npm install`

**Comment by hipstersmoothie** [comment]
Jimp no longer uses phin
