### ISSUE TITLE
problem with the file path when reading the file

### ISSUE THREAD

**Issue by mibijoy007** [jimp-dev/jimp#1298]
# Expected Behavior
![image](https://github.com/user-attachments/assets/8a231ca5-6250-4490-ae21-082dece62a37)
This is what I could see on the docs page. But it doesn't work. I tried many times with difference files, No luck.

# Current Behavior
Then I tried the 'file' name only in the same directory of my srcipt, then it worked.
Also when I tried image source form the web it also works

# Failure Information (for bugs)

**Then it did this:**
Instead of using :

```
**Jimp.read('./path/to/your/file.jpeg')**

// I did:

**Jimp.read('path/to/your/file.jpeg')**

```

then it worked.

So, the problem is just the first   "  . /   "  

which is not a common practice for paths.

========================

- Jimp Version: "jimp": "^0.22.12",
- Operating System: win 10
- Node version: 20.5.1

**Comment by hipstersmoothie** [comment]
I tried both now and they both worked
