### ISSUE TITLE
autocrop cropEmpty: true

### ISSUE THREAD

**Issue by fyyyyy** [jimp-dev/jimp#1299]
**Is your feature request related to a problem? Please describe.**
I'm batch-cropping thousands of sprites from 1024x1024 to around 50-128 px
If a sprite is completely empty  (i.e. only 📗  color) , autocrop does not crop it ( which is correct )
However I would like the option to shrink empty images to 1x1 pixels rather than 1024px.

**Describe the solution you'd like**
`autocrop( { empty: true } )`
or
`autocrop( { empty: '1x1px' } )` // crops empty images to 1x1px

**Describe alternatives you've considered**
I could check the output crop size and replace the image in a callback

Source Example:

<img width="1325" alt="sample" src="https://github.com/user-attachments/assets/d3e5847a-05d4-46d1-a7bf-8639aa47bb2a">

**Comment by hipstersmoothie** [comment]
You could do this simply by setting the height and width of the image

```js
const image = await Jimp.read(getTestImagePath("dice.png"));

image.bitmap.height = image.bitmap.height + 1;
image.bitmap.width = image.bitmap.width + 1;
```
