### ISSUE TITLE
How to migrate to v1?

### ISSUE THREAD

**Issue by archasek** [jimp-dev/jimp#1305]
**Is your feature request related to a problem? Please describe.**
I cannot find Jimp's docs on how to use it in > v1.0.0. Where's it ? :)

**Describe the solution you'd like**
I have the old code I don't know how to migrate:
```
async function optimizeBase64Image(base64Image: string): Promise<string> {
  const image = await Jimp.read(Buffer.from(base64Image, "base64"));
  const resizedImage = await image.resize(512, Jimp.AUTO).quality(80).getBufferAsync(Jimp.MIME_JPEG);

  return Buffer.from(resizedImage).toString("base64");
}
```

**Describe alternatives you've considered**
Tried to find docs, with no success.

**Additional context**
![{1FFC2C44-5E6F-43B8-8F03-5F29CA4DFEC2}](https://github.com/user-attachments/assets/82077d67-d478-432f-98fb-d996b9f0f8fc)

**Comment by hipstersmoothie** [comment]
I've added a migration guide here 

http://jimp-dev.github.io/jimp/guides/migrate-to-v1/

if you find anything else confusing feedback welcome!

**Comment by archasek** [comment]
Thanks so much! <3
