### ISSUE TITLE
`fromBuffer` doesn't work in ESM projects

### ISSUE THREAD

**Issue by benmccann** [jimp-dev/jimp#1308]
# Expected Behavior

Doesn't crash

# Current Behavior

Crashes

# Failure Information (for bugs)

## Steps to Reproduce

Create a new project with `"type": "module"` and then do `await Jimp.fromBuffer(buffer);`

## Context

- Jimp Version: 1.1.0
- Operating System: Linux
- Node version: 20.17.0

## Failure Logs

```
node_modules/.pnpm/@jimp+core@1.1.0/node_modules/@jimp/core/dist/esm/index.js:161
            const mime = await fileType.fromBuffer(actualBuffer);
                                        ^

TypeError: fileType.fromBuffer is not a function
    at Jimp.fromBuffer (node_modules/.pnpm/@jimp+core@1.1.0/node_modules/@jimp/core/dist/esm/index.js:161:41)
```

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.1`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.1) :rocket:

**Comment by benmccann** [comment]
thanks! looks like things are working for me on the v1 release now!

**Comment by hipstersmoothie** [comment]
Sweet, thanks for reporting issues!
