### ISSUE TITLE
[doc] The examples of the migration guide are erroneous

### ISSUE THREAD

**Issue by ghostd** [jimp-dev/jimp#1316]
The [migration guide](http://jimp-dev.github.io/jimp/guides/migrate-to-v1/) contains examples with the old function `getBufferAsync`. In "v1", the new method seems to be `getBuffer`(which is still async)

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.2`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.2) :rocket:
