### ISSUE TITLE
Documentation is incorrect for getBuffer (example)

### ISSUE THREAD

**Issue by sc0Vu** [jimp-dev/jimp#1342]
# Expected Behavior

I believe the example of `getBuffer` would be:

```JS
import { Jimp } from "jimp";
import { promises as fs } from "fs";

const image = new Jimp({ width: 3, height: 3, color: 0xffffffff });

await image.getBuffer("image/jpeg", {
  quality: 50,
});
```

# Current Behavior

The example is not correct (https://github.com/jimp-dev/jimp/blob/main/packages/core/src/index.ts).

# Failure Information (for bugs)

N/A

## Steps to Reproduce

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/0ef139f6-aa64-4101-9fc3-1ff0c972f407">

## Context

- Jimp Version: 1.6.0
- Operating System: N/A
- Node version: N/A

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.6.1`](https://github.com/jimp-dev/jimp/releases/tag/v1.6.1) :rocket:
