### ISSUE TITLE
Jimp.fromBitmap is not a function!?

### ISSUE THREAD

**Issue by Dylan190774** [jimp-dev/jimp#1343]
I'm using Jimp in a browser with Vite and Typescript.

Because `import { Jimp } from 'jimp';` gives an error, I use the following 'hack' to import the library:

```
import 'jimp/browser/lib/jimp';

const { Jimp } = window as Window &
  typeof globalThis & {
    Jimp: typeof import('jimp');
  };

```
This works, because I can now do :
```
        const image = await Jimp.read(
          imageURL,
        );

```

But I want to get data from a canvas, so I try : 
```
        const ctx = canvas.getContext('2d');
        const image = await Jimp.fromBitmap(
          ctx.getImageData(0, 0, canvas.width, canvas.height),
        );
```

But then I get an error message: 
`TypeError: Jimp.fromBitmap is not a function
`
I noticed that `fromBuffer `is also not defined. 

Any idea why these functions are not available, while `Jimp.read `works like a charm?

**Comment by Dylan190774** [comment]
I was still using the 0.22 version. 
I removed the package and added it again and it works now (and without the weird import hack).

**Comment by sc0Vu** [comment]
@Dylan190774 Have you try `import { fromBitmap } from 'jimp'`?

**Comment by Dylan190774** [comment]
It's solved. I now use the 1.6 version.
