### ISSUE TITLE
Multi Layer Support

### ISSUE THREAD

**Issue by aurium** [jimp-dev/jimp#187]
As i told in #166 it should be the right path to animated formats and will be compatible with other use cases.

I think we can add this feature without broke the compatibility with current client code.
* `image.bitmap.data` should refer to current layer data
* `image.bitmap.width` should refer to current layer width
* `image.bitmap.height` should refer to current layer height

The main data source should  be `image.layers` and this list must contain N image data with its related meta-data.
```js
image.layers = [
  <JimpLayer>{ data: <Buffer>, width: <int>, height: <int>, x: <int>, y: <int>, <optional attrs> },
  <JimpLayer>{ data: <Buffer>, width: <int>, height: <int>, x: <int>, y: <int>, <optional attrs> },
  ...
];
```
(`x` and `y` are there because the layer can be placed relatively on the canvas)

Other layer attributes may be: `composition`, `animation delay`, `name`...

The layer object may be an instance of `JimpLayer` and it will have all layer related methods. This layer methods are mostly all current pixel related method, and they can still be liked in both (`Jimp` and `JimpLayer`) prototypes, allow easy manipulation for simple one layer images, and compatible with current user code.

The Jimp image also needs the `canvas` attribute referring to an object with its own `width` and `height` (the real image dimensions). The `canvas` attribute could namespace some canvas related methods.

**Comment by hipstersmoothie** [comment]
I don't think we'll be adding this. you might be interested in https://www.npmjs.com/package/gifwrap
