### ISSUE TITLE
Gradient Color plugin

### ISSUE THREAD

**Issue by aurium** [jimp-dev/jimp#282]
Consider to use http://gka.github.io/chroma.js to know color names, do transformations and render gradients.

**Comment by Iwasawafag** [comment]
Aside from gradients, TinyColor already does all that. What's the benefits?

**Comment by aurium** [comment]
I don't know the difference... chroma.js looks more complete and i want(ed) to compare and consider to use. If you say, i don't need to analyze this. :-)

**Comment by qodesmith** [comment]
Looking fwd to gradient features being developed in the branch mentioned in #659 😃

**Comment by hipstersmoothie** [comment]
This should be covered by canvas functionality #183
