### ISSUE TITLE
Jimp Browser with Web Workers issue when loading font 

### ISSUE THREAD

**Issue by JOscarEduardo** [jimp-dev/jimp#289]
Hi, guys!

Jimp is amazing! I am using it in the server and also in the browser. Recently I decided to use it inside of a web worker. However, when I do that, the Jimp.loadFont fails when trying to load a font. The message is:

```
Error: error parsing font document is not defined
    at Object.callback (jimp.js:4657)
    at cbOnce (jimp.js:8445)
    at loadFunc (jimp.js:8449)
    at XMLHttpRequest.readystatechange (jimp.js:8445)
```

I noticed, in the network pane of chrome console, that the .fnt file is loading correctly. However, the .png file doesn't even appear in the network pane.

I used the same calls and paths (native fonts) that are currently in use and working properly without the Web Worker.

Any hints?

Thanks!

Oscar

**Comment by hipstersmoothie** [comment]
@JOscarEduardo can you provide me some sample code?

**Comment by hipstersmoothie** [comment]
Closing as there was never a repro

**Comment by av01d** [comment]
I am confused... was this issue ever considered? Using fonts in a WebWorker still does not work.
Example worker:
```
importScripts('./jimp.js');

(async () => {

  const font = await Jimp.loadFont('fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt');

  self.addEventListener('message', e => {
    Jimp.read(e.data).then((img) => {
      img.print(font, 10, 10, "Hello World!")
      .getBase64(Jimp.AUTO, (err, src) => {
        if (err) throw err;
        self.postMessage(src);
      });
    });
  });

})();
```
The following error is thrown:
```
jimp.js:2 Uncaught (in promise) Error: error parsing font document is not defined
```
