### ISSUE TITLE
pHash is not real pHash?

### ISSUE THREAD

**Issue by yaneony** [jimp-dev/jimp#337]
I was trying to check out some articles about pHash, and every time i was trying to get hash value from some image, it was different one from what "real" pHash library generated. Is it possible that this implementation of pHash somehow borked?

I checked pHash of "koala1.jpg" from that article http://cloudinary.com/blog/how_to_automatically_identify_similar_images_using_phash and thats totally different from what they have.

**Comment by hipstersmoothie** [comment]
It might be. Why not give it a try and try switching out our implemenation? Make sure to keep it synchronous!
