### ISSUE TITLE
Rotation is weird

### ISSUE THREAD

**Issue by AlexTolmachev** [jimp-dev/jimp#388]
Here's my code:
```
const img = emptyImg.clone()
img.print(font, 20, 20, text, 995)
img.rotate(-9)
```
And this is the result:
![photo0](https://user-images.githubusercontent.com/33148533/34967345-9e4ba702-fa6a-11e7-98a7-dd56e6abbe5b.jpg)

I've tried different fonts, tried another rotation mode and it didn't help. 

I had to add a hotfix to at least somehow minimize the ugliness of these edges:
```
img.scale(3)
img.rotate(-9)
img.scale(0.3333)
```
But this is not an option, you have to understand.

So, what should I do to rotate my text properly?

**Comment by edi9999** [comment]
Indeeed, I agree with this, i think it is due to the fact that no interpolation is done when doing rotation, which causes the image to always "keep" the same pixels, which makes the image look pixelized

**Comment by hipstersmoothie** [comment]
@edi9999 have any ideas on how to fix this?

**Comment by hipstersmoothie** [comment]
So after some reading it seems like we somehow need anti-aliasing on rotation

**Comment by hipstersmoothie** [comment]
this looks like a good solution 

https://www.npmjs.com/package/multimath

look up unsharp mask

**Comment by hipstersmoothie** [comment]
it doesn't seem that anti-aliasing is the solution given the comments here
https://stackoverflow.com/questions/3011274/antialiasing-algorithm

**Comment by hipstersmoothie** [comment]
I think the only solution is to do the scaling described above making sure to use the smallest img possible for the text printing. It seems to have the best results
