### ISSUE TITLE
RangeError: out of range error on 'blur' of a large image

### ISSUE THREAD

**Issue by nosteine** [jimp-dev/jimp#392]
Hi

In my code, I am scaling up an image times 4 and then blurring by a factor of 10:
```
img.resize((img.bitmap.width)*4, (img.bitmap.height)*4)
                .blur(10);
```
This usually works just fine. However, when the image is a big one (e.g. over 600kb and 2881/1200 dimensions), then we get a range error:
**RangeError: Array buffer allocation failed**

You can download this image from the below link and see for yourself:
![https://i0.wp.com/media2.slashfilm.com/slashfilm/wp/wp-content/images/The-Nice-Guys-trailer.jpg](https://i0.wp.com/media2.slashfilm.com/slashfilm/wp/wp-content/images/The-Nice-Guys-trailer.jpg)

Thanks

**Comment by edi9999** [comment]
is the resize the issue or the blur ? Eg what happens if you comment the blur ? Does it still  fail ?

**Comment by nosteine** [comment]
Definately an issue of the blur.
Commenting it out solves the issue

**Comment by nosteine** [comment]
@oliver-moran ? any ideas ?

**Comment by nosteine** [comment]
nothing ?

**Comment by hipstersmoothie** [comment]
@nosteine The image no longer works. can you provide it again?

**Comment by hipstersmoothie** [comment]
I just tried with https://upload.wikimedia.org/wikipedia/commons/2/2d/Snake_River_%285mb%29.jpg (5mb) and it seemed to work. Imma guess this was a problem with jpeg-js. Please try with the latest release. Will be closing this soon if no reply is given

**Comment by hipstersmoothie** [comment]
We could probably find a way to do the blur in a more performant way. maybe using a new jimp instance instead of arrays.
