### ISSUE TITLE
Doesn't support Chinese?

### ISSUE THREAD

**Issue by kreja** [jimp-dev/jimp#419]
I can print English words on images but doesn't work with Chinese.

**Comment by shawmraz** [comment]
@kreja I wanna print Chinese too , do you have any idea? thx

**Comment by hipstersmoothie** [comment]
@kreja @shawmraz It should work if you have a bitmap font that supports chinese characters

**Comment by hipstersmoothie** [comment]
If one of you can provide me with one I can verify if it works

**Comment by tina1998612** [comment]
hi I used a Chinese character font but it doesn't work.. There's no err msg but no text is printed out.

Here is the font:
[font.zip](https://github.com/oliver-moran/jimp/files/3234444/font.zip)

Thanks so much for your help!

**Comment by BlankHrt** [comment]
@tina1998612 
中文字体的问题你解决了吗

**Comment by weiyunpeng** [comment]
中文字体现在怎么处理？

**Comment by peixin7947** [comment]
> 中文字体现在怎么处理？

+1

**Comment by uinnova-wuxin** [comment]
> > 中文字体现在怎么处理？
> 
> +1

+1

**Comment by clcheng199903** [comment]
> 

+1

**Comment by Selenium39** [comment]
+1

**Comment by BraveShadow** [comment]
> hi I used a Chinese character font but it doesn't work.. There's no err msg but no text is printed out.
> 
> Here is the font: [font.zip](https://github.com/oliver-moran/jimp/files/3234444/font.zip)
> 
> Thanks so much for your help!

@tina1998612 Hi, I've downloaded your zip file and tested, maybe the reason that you didn't see printed text is that the color of your font is white!
If you print white words on white base image, of course you cann't see it.
Just change you font color in the fnt file, or change base image to a black image.

**Comment by kedeng** [comment]
1. download ttf file which support chinese characters
2. downlod [bmfont](http://www.angelcode.com/products/bmfont/)
3. open bmfont, goto "Options" -> "Font Settings" --> "Add font file" and choose your ttf file
4. goto "Options" --> "Export Options", Set Bit Depth to 32 and change Presets to "Black text with alpha" or any thing match your requirement, set Textures to "png"
5. click "Options" --> "Save bitmap fonts as ..." and choose your save folder
6. now you can use Jimp.loadFont("the fnt file path") and print chinese

**Comment by azaryahuu** [comment]
> > hi I used a Chinese character font but it doesn't work.. There's no err msg but no text is printed out.
> > Here is the font: [font.zip](https://github.com/oliver-moran/jimp/files/3234444/font.zip)
> > Thanks so much for your help!
> 
> @tina1998612 Hi, I've downloaded your zip file and tested, maybe the reason that you didn't see printed text is that the color of your font is white! If you print white words on white base image, of course you cann't see it. Just change you font color in the fnt file, or change base image to a black image.

hello can you help me with japanese font?

**Comment by azaryahuu** [comment]
> [PingFang_24_BLACK_CHINESE3500.zip](https://github.com/jimp-dev/jimp/files/12414910/PingFang_24_BLACK_CHINESE3500.zip)
> 
> just make a PingFang font with black words and support chinese. including 3500 commonly used Chinese characters , Hope be helpful.
> 
> ```js
> const image = await Jimp.read("http://xxx.png");
> const font = await Jimp.loadFont('PingFang_24_BLACK.fnt');
> image.print(font, 0, 0, "长按观看视频");
> await image.writeAsync('./new.png');
> ```
> 
> ![cc](https://private-user-images.githubusercontent.com/14119424/262323430-63473f01-990f-4616-8ccc-750937c7e194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTQ2MTAsIm5iZiI6MTcxMTExNDMxMCwicGF0aCI6Ii8xNDExOTQyNC8yNjIzMjM0MzAtNjM0NzNmMDEtOTkwZi00NjE2LThjY2MtNzUwOTM3YzdlMTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEzMzE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxY2E4NzMwZWI5NzRlNWUzMjdkNjlhMDdhY2IyMWMzOWQzOWFkMzM5YTY1ZWEyZGNkYmYzODFlMzJjYmIxNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0hlF8pXbsvZ5Dz3v4vZeQfplVSH3mW_sFuDuRLdralU)
> 
> or if you want make your own font:
> 
> 1. download [hiero](https://libgdx.com/wiki/tools/hiero)
> 2. input your words in sample text area
> 3. save BMFont files
> 4. just ust it with Jimp.loadFont

hello good sir can you help me with a japanese font, itried using noto sans from google fonts but im still getting "???"
