### ISSUE TITLE
Module Build needs to export '*.mjs' 

### ISSUE THREAD

**Issue by XkijuX** [jimp-dev/jimp#558]
Ok so this is the error
 ```
c:\Users\koubi\Desktop\rotmg-meteor\node_modules\jimp\es\index.js:35
import FS from 'fs';
SyntaxError: Unexpected token import
```

How i got it:
```
import Jimp from 'jimp/es';
```

im using this version of jimp
`` "jimp": "^0.3.5",``

im on **meteor** with **node.js** both should be up to date

**Comment by hipstersmoothie** [comment]
the module version of jimp should only be used in environment supporting it. I've gotten it working with webpack. Does meteor support module builds? Otherwise just import 'jimp'

**Comment by hipstersmoothie** [comment]
There does seem to be a bug in our module build though. the files should end with `.mjs` for node.

**Comment by soimy** [comment]
Any updates on this?
Just tried `import Jimp from "jimp/es"` and vscode cried for not found d.ts file.

**Comment by hipstersmoothie** [comment]
should be better now? open a new issue if it isnt
