### ISSUE TITLE
Create @jimp/web-worker

### ISSUE THREAD

**Issue by hipstersmoothie** [jimp-dev/jimp#602]
# Expected Behavior

Jimp loaded in a webworker and easy to use

# Current Behavior

Jimp loads in browser and slow things down

**Comment by edi9999** [comment]
+1 !

Being a separate package makes a lot of sense,

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.5`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.5) :rocket:
