### ISSUE TITLE
Rotation command gives opposite results

### ISSUE THREAD

**Issue by MerriemWeebster** [jimp-dev/jimp#631]
I'm not sure if this is a bug or a change, but I recently updated Jimp again after a long time and have a issue with the rotate command.

When I use image.rotate(-3) I expect the image to be rotated 3 degrees anti-clockwise. Instead, it rotates clockwise.

A similar case happens when I use image.rotate(20), it rotates anti-clockwise instead of clockwise.

Basically I get the opposite result of what I expect...

- Jimp Version: 0.5.3

**Comment by omkar-joshi** [comment]
@hipstersmoothie Any update on this? I'm facing the same issue. Also, I'm not sure why I'm getting a border around the rotated image. It can be seen in the repro given in #669. It would be great if this gets fixed in the next release.

**Comment by omkar-joshi** [comment]
@hipstersmoothie I can pick this up and would be happy to submit a PR ✌️

**Comment by hipstersmoothie** [comment]
go for it! @omkar-joshi

**Comment by hipstersmoothie** [comment]
just be warned about the tests though. lots of updating to do

**Comment by MerriemWeebster** [comment]
Issues with this still occur

**Comment by MerriemWeebster** [comment]
Exact same problem, no changes

**Comment by MerriemWeebster** [comment]
@hipstersmoothie any luck with a solution?

**Comment by MerriemWeebster** [comment]
**CURRENT SOLUTION**
Been dealing with this issue since 0.2 so I have a solution for those that have been struggling with this. Once solution is to call the .rotate function with the number of degrees you want but multiply it by -1, but the best solution to make this easier for the developer is to do the following:

1. In your node_modules folder for your base project, you will find a folder called **@jimp**, in this folder, go to **plugin-rotate**, then to **dist** and finally open **index.js**
2. Go to line **147**, you will find the following code: `advancedRotate.call(this, deg, mode, cb);`. Simply change this line to `advancedRotate.call(this, -deg, mode, cb);`.

For some reason, the base calculation in the advancedRotate function does all the rotations anticlockwise rather that clockwise. I'd rather not mess with the base code but a simple solution like this is better than messing with everything else.

**Comment by hipstersmoothie** [comment]
@MerriemWeebster it's a bug that you could fix :D simply make a pr and everyone can benefit from your findings

**Comment by MerriemWeebster** [comment]
> @MerriemWeebster it's a bug that you could fix :D simply make a pr and everyone can benefit from your findings

Not sure what you mean by pr, but I did make a suggestion for [a fix](https://github.com/oliver-moran/jimp/commit/a31c2a325adbb634e96dbbe140288f5dd97eabdd)

**Comment by MerriemWeebster** [comment]
> **CURRENT SOLUTION**
> Been dealing with this issue since 0.2 so I have a solution for those that have been struggling with this. One solution is to call the .rotate function with the number of degrees you want but multiply it by -1, but the best solution to make this easier for the developer is to do the following:
> 
> 1. In your node_modules folder for your base project, you will find a folder called **@jimp**, in this folder, go to **plugin-rotate**, then to **dist** and finally open **index.js**
> 2. Go to line **128**, you will find the following code: `advancedRotate.call(this, deg, mode, cb);`. Simply change this line to `advancedRotate.call(this, -deg, mode, cb);`.
> 
> For some reason, the base calculation in the advancedRotate function does all the rotations anticlockwise rather that clockwise. I'd rather not mess with the base code but a simple solution like this is better than messing with everything else.

It seems that this solution stopped working and requires a few additional steps. There are

**Comment by MerriemWeebster** [comment]
> **CURRENT SOLUTION**
> Been dealing with this issue since 0.2 so I have a solution for those that have been struggling with this. One solution is to call the .rotate function with the number of degrees you want but multiply it by -1, but the best solution to make this easier for the developer is to do the following:
> 
> 1. In your node_modules folder for your base project, you will find a folder called **@jimp**, in this folder, go to **plugin-rotate**, then to **dist** and finally open **index.js**
> 2. Go to line **128**, you will find the following code: `advancedRotate.call(this, deg, mode, cb);`. Simply change this line to `advancedRotate.call(this, -deg, mode, cb);`.
> 
> For some reason, the base calculation in the advancedRotate function does all the rotations anticlockwise rather that clockwise. I'd rather not mess with the base code but a simple solution like this is better than messing with everything else.

Sorry for reopening and opening this multiple times, but just wanted to make sure that if anyone finds this issue, know that this solution still works, sometimes even I forget about it and google the issue and use my own answer after all the code changes when I update it. I do hope it can be looked into as to why this solution is needed in the first place and thus I will keep this issue open for those that may have a similar problem but are unable to make use of my solution.

**Comment by MerriemWeebster** [comment]
Also keeping this open since I have not gotten a reply as to why such an issue occurs in the first place or for a permanent solution based on the fix I requested.

> > @MerriemWeebster it's a bug that you could fix :D simply make a pr and everyone can benefit from your findings
> 
> Not sure what you mean by pr, but I did make a suggestion for [a fix](https://github.com/oliver-moran/jimp/commit/a31c2a325adbb634e96dbbe140288f5dd97eabdd)

**Comment by csorfab** [comment]
> @MerriemWeebster you're right. getting a PR to change this together. Lots of broken tests though!

At this point would you consider a PR that updated the docs to reflect the anti-clockwise behavior of .rotate()? I just started using this project, and I don't really care which way the function works, but it was really frustrating to have to dig through issues to find out what's going on, so in the meantime, would you accept a PR updating the docs to say "anti-clockwise" instead of "clockwise"?

**Comment by fabb** [comment]
I agree, the documentation should be fixed. I created a PR: #1062

**Comment by hipstersmoothie** [comment]
Docs fixed now, thanks @fabb!
