### ISSUE TITLE
LosslessJpegDecoder is undefined

### ISSUE THREAD

**Issue by chris-maclean** [jimp-dev/jimp#647]
# Expected Behavior
Jimp should be able to process DNG files.

# Current Behavior
Jimp throws an error `LosslessJpegDecoder is undefined`. 

# Failure Information (for bugs)
```javascript
import Jimp from 'jimp';
```

I'm using Jimp within an AWS Lambda function. When I import Jimp to perform conversion on a DNG to base64, I get the error `LosslessJpegDecoder is undefined`. This occurs before I perform any image processing.

I've found the line in `jimp.js` that appears to instantiate a `LosslessJpegDecoder`, and I can't see where a `LosslessJpegDecoder` would be defined. From jimp@0.4.0, `jimp.js:31737`:

```javascript
	if(img["t262"]==32803) // lossless JPEG (used in DNG files) is not available in JpegDecoder.
	{
		var bps = img["t258"][0], dcdr = new LosslessJpegDecoder();
```

I can't find any references to `LosslessJpegDecoder` anywhere else in the code. Where is this supposed to come from?

I have found a snippet of code identical to the snippet above in the `utif` package (https://github.com/photopea/UTIF.js/blob/master/UTIF.js). I believe Jimp uses  `utif` but I'm not sure how. It's possible that this is `utif`'s problem, not Jimp's, but since I'm not directly relying on `utif` I thought I would open this issue.

## Steps to Reproduce
1. Import jimp in an AWS Lambda function.

**Screenshots**

## Context

This problem occurs in an AWS Lambda function.

- Jimp Version: 0.4.0
- Operating System: AWS Lambda ... probably AmazonLinux
- Node version: 8.10

## Failure Logs
```2018-10-24T15:00:40.166Z - error: Error in vision processing LosslessJpegDecoder is not defined```

# Notes
It's possible that this is a `utif` problem, not a `jimp` problem, but since they contain some identical code I wanted to ask in both places. Thank you for your help.

**Comment by hipstersmoothie** [comment]
This is def a problem with utif. I can put together a small example for an
issue there but I am currently away from a computer. Are you using the
latest jimp? 0.4.0 is old

**Comment by c-anna** [comment]
Looks like I am not using the latest jimp. npmjs.org says 0.4.0 is about 2 months old, which sounds like about the time I started on this function. I'll upgrade to the latest and see if that does anything (I doubt it, since the code currently in Github looks the same as what I posted).

Thank you so much! I have an issue open on the `utif` project here: https://github.com/photopea/UTIF.js/issues/49

**Comment by c-anna** [comment]
The devs at UTIF.js replied to me: https://github.com/photopea/UTIF.js/issues/49#issuecomment-432802236

Looks like DNGs are outside the purview of UTIF.js. Does that mean that it's also outside the purview of Jimp? Do the Jimp developers think it should decode DNG files?

When I filed this issue, I thought that I had been processing DNGs with Jimp for some time. After some investigation, I realized that's not the case -- only within the last couple days have I been processing DNGs with Jimp, and that's when this problem started. If Jimp is simply not a tool for processing DNGs, I'll have to find another way to do it. If Jimp is _supposed_ to be able to process these files, I'll await guidance from the dev team.

**Comment by hipstersmoothie** [comment]
I did not realize DNG was an image type. Jimp does not support that image. If you wrote a encoder/decoder in JS though it would be easy to integrate. 

Jimp supports the following image types: 


bmp
gif
jpeg
png
tiff

**Comment by hipstersmoothie** [comment]
So if you want to add it feel free to make a PR and i will guide you on how to do it. Otherwise processing this image file is outside the scope of jimp. Close? or would you like me to keep it open to track DNG?

**Comment by c-anna** [comment]
That sounds like an interesting project, I think I can do it. There already exists a package `lossless-jpeg-decoder` (https://www.npmjs.com/package/lossless-jpeg-decoder) that can probably handle the heavy lifting of decoding. What do I need to do to integrate such a decoder into Jimp?

**Comment by c-anna** [comment]
In fact, @rdhenderson solved the problem for our team with some webpack wizardry, basically providing `LosslessJpegDecoder` as a peer dependency (tying it to `lossless-jpeg-decoder`). So I know that I won't have to reinvent the wheel re:DNG decoding (which I know nothing about), I'll just need to integrate that package into Jimp.

Any help/guidance is appreciated! Thank you!

**Comment by hipstersmoothie** [comment]
Awesome that you got it working! As for adding it to jimp you will probably add it as a dependency to this package https://github.com/oliver-moran/jimp/tree/master/packages/jimp. 

You might be able to just add it? I'm not quite sure how to go about it. The hard part is going to be the UTIF.js just uses `LosslessJpegDecoder` and doesn't require or import it. So just installing the dependency won't effect that. Thats why you guys had to do it with webpack.

It seems like UTIF.js needs to:

* require the LosslessJpegDecoder somehow
* add `lossless-jpeg-decoder` as a peer dep

That will make installing the dependancy in jimp work without too much overhead. I have publish access to UTIF. So if you get something merged over there i can get it out quickly.

**Comment by c-anna** [comment]
I agree that modifying UTIF.js is an attractive solution. If I could modify UTIF.js, adding `lossless-jpeg-decoder` as a dependency and sticking

```javascript
LosslessJpegDecoder = require('lossless-jpeg-decoder')
```

at the top of UTIF.js would solve the problem. But the folks at Photopea (or at least the person who replied to my issue) doesn't want to support DNG (https://github.com/photopea/UTIF.js/issues/49#issuecomment-432802236):

> I don't want all users of UTIF.js attach LosslessJpegDecoder to their files, because they will not need it for decoding regular TIFF files. I hope you will be able to attach it somehow in your own environment.

I guess that's fair enough, they may not want their project to accumulate features that randos on the internet like me decide it should have. I will mention the above fix and see if that is still out of bounds.

If they're not interested in supporting this, do you think there's a way forward that only requires changes to Jimp? I will continue thinking on it.

**Comment by hipstersmoothie** [comment]
The guys that run hat toe to really don’t understand npm so be wary

**Comment by hipstersmoothie** [comment]
Maybe look into optional dependencies. You could use require ensure to check for the package and then require it before he call the lossless jpeg decoder. The user could still optionally install the dep and we wouldn’t have to do anything with webpack

**Comment by rdhenderson** [comment]
I initially tried to resolve the problem by using webpack to inject LosslessJpegDecoder as a global variable with shimming.  Downside to that approach was it required webpacking node modules which felt like a hack.  I ended up using a simple post install hook to inject a require statement into utif.js if it wasn't present, and that does the trick nicely. 

```
STMT="const LosslessJpegDecoder = require('lossless-jpeg-decoder');"
FILE=node_modules/utif/UTIF.js 
if ! grep -Fxq "$STMT" $FILE; then
  echo 'Injecting lossless jpeg decoder into utif package'
  sed -i '' "1s/^/$STMT/" $FILE
fi
```
Will look into a better solution for UTIF package generally and try for a PR

**Comment by hipstersmoothie** [comment]
@rdhenderson look at my last comment. This should work and be okay with the utif team

**Comment by rdhenderson** [comment]
@hipstersmoothie Awesome - I've run across that in the docs, but haven't used it in the wild. Should be perfect, thanks!

**Comment by rdhenderson** [comment]
[PR](https://github.com/photopea/UTIF.js/pull/51) submitted on UTIF.js

**Comment by hisham** [comment]
This is still an issue right? I'm running 0.16.1 and it still can't process dng files.

**Comment by rdhenderson** [comment]
Seems possible, the maintainer for UTIF.js did not like the PR I proposed to fix the issue -- said he pulled in the minified library instead.  If so, you should be able to install the dependency and use your method of choice to add the require statement in UTIF.js (as outlined above).  If you're having trouble, I can double check how we're handing that currently

**Comment by hisham** [comment]
Thanks @rdhenderson. Yes it works - all that's needed is for @jimp/type-tiff to update its utif dependency to 3.1.0.

In the meantime I just installed the latest utif as a dependency on my project and overwrote the UTIF decoder with as follows: 

```
    Jimp.decoders[Jimp.MIME_TIFF] = (data: Buffer) => {
      const ifds = UTIF.decode(data);
      const page = ifds[0];
      UTIF.decodeImage(data, page);
      const rgba = UTIF.toRGBA8(page);

      return {
        data: Buffer.from(rgba as ArrayBuffer),
        width: page.width,
        height: page.height,
      };
    };
```

**Comment by hipstersmoothie** [comment]
Does this work now?
