### ISSUE TITLE
Any feature about converting Multiple images to Single GIF?

### ISSUE THREAD

**Issue by mani-Shankar** [jimp-dev/jimp#671]
Hi,

Is there any feature related to converting multiple images to single GIF? 

if so please provide the solution regarding this. 

Thanks

**Comment by hipstersmoothie** [comment]
This is not supported at the moment. GIF support is quite limited (I've never tried it). I would suggest looking into https://www.npmjs.com/package/gifwrap. It aims to manipulate images in a jimp compatible way.
