### ISSUE TITLE
Jimp.rgbaToInt() requires a callback on TypeScript declaration

### ISSUE THREAD

**Issue by arj-mat** [jimp-dev/jimp#684]
TypeScript declaration https://github.com/oliver-moran/jimp/blob/master/packages/jimp/jimp.d.ts is requiring a callback function within the arguments for **Jimp.rgbaToInt**.

![image](https://user-images.githubusercontent.com/5123733/50551927-4aa97200-0c70-11e9-8994-6f468c580b5f.png)

Since cb is an optional argument on Jimp.intToRGBA, it could be for Jimp.rgbaToInt as well.
The wanted number is properly returned when making cb optional on the reported declaration line.

**Comment by hipstersmoothie** [comment]
this is fixed
