### ISSUE TITLE
Autocrop south not always working correct. Tolerance has no effect.

### ISSUE THREAD

**Issue by JR-Y** [jimp-dev/jimp#696]
# Expected Behavior
Auto crop should crop all sides (north,east,west,south) in the same way. And tolerance value should have some effect.

# Current Behavior
In my latest use cases the south auto crop seems to sometimes not stop at the same color difference as the others. Hence south is cropped approximately 1 - 20 % too much. 

Also the tolerance value only has an effect at the value 1, if I try 0.5 for example this does nothing compared to 0.0002

# Failure Information (for bugs)
Images, one that works normally and another that does not. I tried to choose similar images to give a fair comparison.

![80039_isometric_cropped](https://user-images.githubusercontent.com/24767278/51374333-62577600-1b0b-11e9-98e1-1dbb4ccd4059.jpg)
![80039_isometric](https://user-images.githubusercontent.com/24767278/51374437-ae0a1f80-1b0b-11e9-8e63-18faa97c9698.JPG)
![60279_isometric_cropped](https://user-images.githubusercontent.com/24767278/51374454-bbbfa500-1b0b-11e9-88ab-6ceadaaa6602.jpg)
![60279_isometric](https://user-images.githubusercontent.com/24767278/51374464-c67a3a00-1b0b-11e9-815c-d67869da48c2.JPG)

## Steps to Reproduce

I tried to set everything to "default". Did:

var Jimp = require('jimp');

Jimp.read('testimage.jpg', (err, image) => {
  if (err) throw err;
  image.autocrop({
             tolerance: 0.0002,
             leaveBorder: 10
                 }) 
    .write('testimage_out.jpg'); // save
});

**Screenshots**

## Context

- Jimp Version: 0.6.0
- Operating System: W10
- Node version: 8.11.2

## Failure Logs

none

**Comment by rolero** [comment]
Any update on this issue? We experience exactly the same issue:


![image](https://user-images.githubusercontent.com/2805313/66254458-0623a780-e7a9-11e9-96ee-b53bdc0a9d86.png)

![image](https://user-images.githubusercontent.com/2805313/66254459-0b80f200-e7a9-11e9-8164-3c302ad01359.png)

Code:
![image](https://user-images.githubusercontent.com/2805313/66254476-26536680-e7a9-11e9-90c9-d6314351a87a.png)

**Comment by tgrajewski** [comment]
This is the same issue as #717 and #651.

**Comment by hipstersmoothie** [comment]
Merging into #651
