### ISSUE TITLE
Jimp read from a GridFSBucketReadStream

### ISSUE THREAD

**Issue by eliomaria** [jimp-dev/jimp#697]
**Describe the solution you'd like**
I would like to be possible for jimp to read the Stream that GridFS created on reading a file from mongoDB.

**Describe alternatives you've considered**
I tried to convert the stream to a buffer to later create a stream from jimp, but always with errors from the buffer reading.

**Comment by hipstersmoothie** [comment]
Can i get sample code? What mime type is your buffer?

**Comment by eliomaria** [comment]
Hey, i got it to work, but for that i need to get the buffer from the stream, use it to create a Jimp object to resize and then convert it again to a buffer so i can send it from my response.

Here is the function:

     // This gets the GridFSBucketReadStream form my mongoDB
      const gridFSBucketReadStream = this.fileRepository.get(id);
      const concat = [];
      gridFSBucketReadStream.on('data', data => {
        concat.push(data);
      });
      gridFSBucketReadStream.on('end', async () => {
        const buffer = Buffer.concat(concat);
        const image = await Jimp.read(buffer);
        const mime = image._originalMime ? image._originalMime : Jimp.MIME_JPEG;
        image.resize(150, Jimp.AUTO).getBuffer(mime, (err, buffer) => {
          if (err) reject(err);
               response.set('Content-Type', mime);
               response.send(buffer);
        });
      });
    });



The problem is that request gets too slow this way, from all those conversions. A request for an image that i can simple pipe the GridFSBucketReadStream, that takes 50ms, turns in a 600ms request this way.

Any idea how to optimize this? Seems to me like a lot of unnecessary transformations.

**Comment by hipstersmoothie** [comment]
I don't really see any way of doing less transformations. It's already pretty lean 

GridFSBucketReadStream -> buffer -> jimp stuff -> buffer

What optimization do you think is possible?
