### ISSUE TITLE
* > CssColor, CssColor > *

### ISSUE THREAD

**Issue by seiyria** [jimp-dev/jimp#701]
**Is your feature request related to a problem? Please describe.**
It's a bit odd that there is no functions to convert _to_ a CSS Color, but there is rgbatoint, inttorgba, etc. 

**Describe the solution you'd like**
Would be nice to rgba->css, int->css, css->int, css>rgba for completeness.

**Describe alternatives you've considered**
Writing it myself, but I think it'd fit in this lib.

**Comment by hipstersmoothie** [comment]
PRs welcome! I like the idea

**Comment by hipstersmoothie** [comment]
We aren't a color library and will probably remove those function and recommend a good color library. #1146
