### ISSUE TITLE
Issue with text scaling.

### ISSUE THREAD

**Issue by Ryzenfire** [jimp-dev/jimp#705]
Hey im sorry for ignoring the template. 

but I
 am having an issue I can't find a fix too.

How would someone scale text

I know you can scale images but I can't seem to figure it out,

thx for reading.

it should look like 
![rank 1](https://user-images.githubusercontent.com/37125308/53263288-8c69fe00-369e-11e9-941d-6db4544e32ad.png)

but it looks like 
![rank](https://user-images.githubusercontent.com/37125308/53263296-912eb200-369e-11e9-83fd-852af670c0be.png)

**Comment by hipstersmoothie** [comment]
I am unsure of what is wrong in the example image. To scale text you could write the text to it's own Jimp instance, resize it, then composite the text image onto your base image. The best solution would probably be to include the appropriately sized font though
