### ISSUE TITLE
Replacing Lenna as an example image

### ISSUE THREAD

**Issue by hanbyul-here** [jimp-dev/jimp#711]
**Is your feature request related to a problem? Please describe.**
Please see the context below. 

**Describe the solution you'd like**
Use something other than [Lenna](https://github.com/oliver-moran/jimp/blob/master/packages/jimp/browser/examples/lenna.png) for examples.

**Describe alternatives you've considered**
How about one from [Kodak image collection](https://github.com/lemire/kodakimagecollection)?

**Additional context**
Thanks for all the hard works on Jimp. While going through docs, I noticed that you are using Lenna as an example image. I believe the history of the image ( [link for Wikipedia article](https://en.wikipedia.org/wiki/Lenna) )  goes against [code of conduct](https://github.com/oliver-moran/jimp/blob/master/CODE_OF_CONDUCT.md) of this repo. 

Leaving this link for more context: https://www.tandfonline.com/doi/full/10.1080/09500340.2016.1270881

**Comment by drewda** [comment]
+1

Also more backstory in the article at https://www.theatlantic.com/technology/archive/2016/02/lena-image-processing-playboy/461970/

**Comment by hipstersmoothie** [comment]
Totally down for it! Just don't have the time to do it myself. Feel free to make a PR!

**Comment by hipstersmoothie** [comment]
Done 🚀
