### ISSUE TITLE
IE11: Automation server can't create object

### ISSUE THREAD

**Issue by trszdev** [jimp-dev/jimp#716]
# Expected Behavior

Not getting error `Automation server can't create object` in Internet Explorer 11

# Current Behavior

Error occurs when I'm trying to `importScripts('jimp.min.js')` in web worker (v0.6.0 as mentioned in license but seems to be 0.6.1)

# Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/9008471/55461480-f961a380-560d-11e9-82a8-cc6508eb113f.png)

(hex name because of mine webpack setting, its ok)

## Steps to Reproduce

1. create file worker.js with contents: `importScripts('jimp.min.js')`
2. in main javascript file write: new Worker('worker.js')

## Context

- Jimp Version: 0.6.0
- Operating System: Windows 
- Node version: none
- Browser: Internet Explorer 11
![image](https://user-images.githubusercontent.com/9008471/55461654-6a08c000-560e-11e9-94d4-0898f0cd9e94.png)

**Comment by hipstersmoothie** [comment]
ie11 is holding the modern web back and even at my job with millions of customers we have decided to not support it anymore. I won't do the work to make jimp work in IE but if you want to submit a PR I'll merge it. But you could probably do that transpilation on your end as well

🚀 Let IE Die! 🚀
