### ISSUE TITLE
Read buffer

### ISSUE THREAD

**Issue by Gwynbleidd79** [jimp-dev/jimp#744]
I tried to save the buffer on a database to read it later, but the things i'm trying isn't working.

I tried to do this:

          var imgs = ['./test1.png', './test2.png'];
          const jimps = await Promisse.all(imgs.map(img => Jimp.read(img)));

          jimps[0].resize(500, 500);
          jimps[1].resize(270, 270);

         jimps[0].composite(jimps[1], 0, 0);

        data.test = jimps[0].getBase64Async(Jimp.AUTO).slice(22);  // slice(22) is to cut the "data:image/png;base64,"

Then:

         const jimps2 = await Jimp.read(Buffer.from(data.test));

And i got the error "Could not find MIME for buffer (null)"
I'm saving the base64 as a string on database, also tried the function "getBufferAsync" but saved as a string 'cause  i don't know what type the buffer is.

Edit* with "getBufferAsync" i got err too.

**Comment by UnHumbleBen** [comment]
Any update?

**Comment by hipstersmoothie** [comment]
merging into #738
