### ISSUE TITLE
synchronization or asynchronization

### ISSUE THREAD

**Issue by wudi00** [jimp-dev/jimp#747]
Is jimp executed asynchronously? I use `var b64 = openimage(x1,y1, x2-x1, y2-y1);` call such function `async function openimage(x, y, w, h){
    console.log("START");
    await Jimp.read("./S_10.png")
        .then(await function (images) {
            images.crop(x, y, w, h);
            images.getBase64(Jimp.AUTO, function(err,data){
                da = data;
            });
        }).catch(function (err) {
            // handle an exception
            console.log("ERR: ",err);
        });
        console.log(da);
        return da;
}` It could not return the results immediately, It's done in the main function, why?

**Comment by wudi00** [comment]
May I turn jimp.read into synchronous function ?

**Comment by hipstersmoothie** [comment]
merging into #1181
