### ISSUE TITLE
undefined is not an object (evaluating 'gl.Jimp = Jimp')

### ISSUE THREAD

**Issue by Josh2941** [jimp-dev/jimp#761]
Getting this error **"undefined is not an object (evaluating 'gl.Jimp = Jimp')"** while starting the app. Not even able to run the app

# Expected Behavior
The app should run successfully. 

# Current Behavior
Error:  undefined is not an object (evaluating 'gl.Jimp = Jimp')

# Failure Information (for bugs)

## Steps to Reproduce
1. Install jimp
2. Run the app
3. You get this error: undefined is not an object (evaluating 'gl.Jimp = Jimp') 

**Screenshots**
![Screenshot_20190720-183609](https://user-images.githubusercontent.com/34862136/61579112-7ada3480-ab1e-11e9-88eb-b71b83e46ee5.png)

## Context
- Jimp Version: 0.6.4
- Operating System: Ubuntu 16.10
- Node: 10.15.3
- npm: 6.4.1
- react: 16.8.3 
- react-native: 0.59.3

**Comment by daniocean** [comment]
Strangely it works if you have the debugger enabled, but otherwise, I encounter the same problem

**Comment by HaywoodSolutions** [comment]
Any updates on this issue?

**Comment by vicki15** [comment]
Yup, it works on iOS fine for my react-native application, but when trying to run on Android I see this error.

**Comment by moconnor59** [comment]
Same problem here - both on iOS and Android (using Expo).

I'm using Jimp v0.10.2, the stack trace looks slightly different (attached) but the result is the same.
![Screenshot_20200419-182311](https://user-images.githubusercontent.com/19475175/79695216-7e494a80-826d-11ea-94bd-c8f171f3bec1.png)

**Comment by moconnor59** [comment]
Same problem here - both on iOS and Android (using Expo).

I'm using Jimp v0.10.2, the stack trace looks slightly different (attached) but the result is the same.
![Screenshot_20200419-182311](https://user-images.githubusercontent.com/19475175/79695216-7e494a80-826d-11ea-94bd-c8f171f3bec1.png)

**Comment by marvinruder** [comment]
Thanks for reporting this bug, @Josh2941! We are currently investigating several issues with Jimp in frontend tools such as React [Native], and will consolidate the discussion there. We will therefore close this issue as duplicate, but continue to work on a fix. You can follow the progress on that in #1194.
