### ISSUE TITLE
[Request] Add information about garbage collection to documentation

### ISSUE THREAD

**Issue by OutsourcedGuru** [jimp-dev/jimp#762]
**Is your feature request related to a problem? Please describe.**
I put a Jimp-based daemon into service but noticed that the memory related to it would climb but rarely return to the original level when it started. For a moment, I started thinking about perhaps using a `crontab` to periodically restart the service to return that memory.

My code—at the moment at least—performs three levels of `convolute()` with a blur kernel. The underlying graphic at the beginning is about 184K each. Those convolute's happen in an asynchronous waterfall within Node.

Even if I used the JavaScript `delete imgJimp` inside the innermost code of that waterfall, I was noticing that the memory wasn't getting returned.

I eventually managed to expose the garbage collection within Node so that I could force the issue.  The high-water mark of memory for blurring nine graphics like this was as much as 200MB (and on a Raspberry Pi 3B with 1GB of memory that's significant).

**Describe the solution you'd like**
It would be great if the documentation could talk about the memory cost of Jimp objects and ways of returning the memory back to the heap as soon as possible.

`node --expose-gc index.js`

```
  ...
  delete imgBlur3rd;
  delete imgBlur2nd;
  delete imgBlur1st;
  delete imgIn;
  try {
    if (global.gc) {global.gc();}
  } catch (e) {
    console.log("Error: the --expose-gc argument was missing: `node --expose-gc index.js`");
  }  
```
**Describe alternatives you've considered**
I considered adding a `crontab` entry to do something like `sudo service blurd restart` on the hour.

**Additional context**
It's likely that most people don't even think of the impact of their program if it's a service.

**Comment by awaismehmood88** [comment]
That is what I was looking for
 if (global.gc) {global.gc();}

**Comment by Art3miX** [comment]
#906 

It seems to be a memory leak, and related to my issue.

**Comment by hipstersmoothie** [comment]
Merging into https://github.com/jimp-dev/jimp/issues/906
