### ISSUE TITLE
utf8 in jimp

### ISSUE THREAD

**Issue by IdkWhosThis** [jimp-dev/jimp#768]
# Expected Behavior

I want to write text on image using jimp with diacritics (ěščřžýáíé).

# Current Behavior

It worked fot í, bot not for ě, ž and ů (i got ? instead of ě, ž and ů).
![image](https://user-images.githubusercontent.com/39670563/62424562-8a39b000-b6d0-11e9-9c7b-90d8a685b806.png)

## Context

My code:
```js
let font = await jimp.loadFont(jimp.FONT_SANS_32_WHITE) //We declare a 32px font
  let font64 = await jimp.loadFont(jimp.FONT_SANS_64_WHITE) //We declare a 64px font
  let bfont64 = await jimp.loadFont(jimp.FONT_SANS_64_BLACK)
  let mask = await jimp.read('https://i.imgur.com/552kzaW.png') //We load a mask for the avatar, so we can make it a circle instead of a shape
  let welcome = await jimp.read('http://rovettidesign.com/wp-content/uploads/2011/07/clouds2.jpg') //We load the base image

  jimp.read(member.user.displayAvatarURL).then(avatar => { //We take the user's avatar
    avatar.resize(200, 200) //Resize it
    mask.resize(200, 200) //Resize the mask
    avatar.mask(mask) //Make the avatar circle
    welcome.resize(1000, 300)

  welcome.print(font64, 265, 55, `Vítej, ${member.user.username}`) //We print the new user's name with the 64px font
  //welcome.print(bfont64, 265, 125, `To ${member.guild.name}`)
  welcome.print(font, 265, 195, `Aktuálně je tu ${member.guild.memberCount} uživatelů!`)
  welcome.composite(avatar, 40, 55).write('Welcome2.png') //Put the avatar on the image and create the Welcome2.png bot
  try{
  member.guild.channels.find(c => c.name === "welcome").send(``, { files: ["Welcome2.png"] }) //Send the image to the channel
  }catch(e){
	  // dont do anything if error occurs
	  // if this occurs bot probably can't send images or messages
  }
})
```

- Jimp Version: 0.6.4
- Operating System: Ubuntu 16.04
- Node version:

**Comment by yoavapi** [comment]
Any idea how to solve it?

**Comment by danielperez9430** [comment]
The solution is simple, just create a new font with the missing characters.

Steps:
1- Download Hiero -> [https://libgdx.badlogicgames.com/nightlies/runnables/runnable-hiero.jar](https://libgdx.badlogicgames.com/nightlies/runnables/runnable-hiero.jar)
2- Check if you have java installed
2- Run it from console: `java -jar runnable-hiero.jar`
3 - Select Font, Size, ... and Press **Extended** (This makes you have support for all the characters that the font supports)
![imagen](https://user-images.githubusercontent.com/10388515/99902725-3f2a1e80-2cc0-11eb-88b0-4f620269df09.png)

4 - Save font 
![imagen](https://user-images.githubusercontent.com/10388515/99902804-c7a8bf00-2cc0-11eb-89cb-a22fbe2fd00f.png)

Once this is done, a .fnt file and some png images will be saved. Like this:

![imagen](https://user-images.githubusercontent.com/10388515/99902849-08083d00-2cc1-11eb-82ae-9d946b0701ec.png)

Now you just load the font using **loadFont**:

`jimp.loadFont('fonts/arial_64_white.fnt');`
 
And with this you have the problem solved 😄

**Comment by IdkWhosThis** [comment]
Thanks for reply, but I already moved to Canvas, because jimp is just a trash.

**Comment by Ronkiro** [comment]
I actually tested @danielperez9430 solution and it worked. Please note that you can *still* save the script file in wrong encoding lol
