### ISSUE TITLE
Jimp constructor with buffer data throws exception.

### ISSUE THREAD

**Issue by likwifi** [jimp-dev/jimp#776]
I'm trying to create new image with another images' buffer data.
As per docs this code should work
```
new Jimp({ data: buffer, width: 1280, height: 768 }, (err, image) => {
  // this image is 1280 x 768, pixels are loaded from the given buffer.
});
```
however this throws following error.

> No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.

Jimp version 0.6.4

My buffer is another images's bitmap.data

**Comment by meepen** [comment]
having the same issue as this, is there any known workaround?

**Comment by VirtualTim** [comment]
I way hoping to use this in the way described in the comment below, but ran into this bug too.

https://github.com/oliver-moran/jimp/issues/303#issuecomment-417991976

**Comment by hipstersmoothie** [comment]
merging into #303
