### ISSUE TITLE
unhandled crash on read image large file (ex. tif@185Mo)

### ISSUE THREAD

**Issue by Akos13** [jimp-dev/jimp#796]
Try to read large file (ex. tif@185Mo) for jimp operations

Unable to read file, nodeJs low level crash (sorry, it was unable to handle the error!)

to reproduce, do jimp.read(filetest) with filetest in tif@185Mo (5603x3735 or more)
node crash...

- Jimp Version: 0.8.2
- Operating System: unbutu 19.04 or Windows 10
- Node version: 12.10

**Comment by hipstersmoothie** [comment]
If you want more accurate image codecs please use the WASM ones. The exact issue here is probably an issue with one of the default JS based codecs.
