### ISSUE TITLE
I want sharpness, UnsharpMask plugin

### ISSUE THREAD

**Issue by nakawankuma** [jimp-dev/jimp#809]
**Is your feature request related to a problem? Please describe.**
I have been request for a sharpening function.

**Describe the solution you'd like**
.sharp(power: number)
I filter sharpness to image.

**Describe alternatives you've considered**
https://github.com/lovell/sharp
sharpen method.
but that library is not javascript only.

**Comment by stephan-fischer** [comment]
yes a sharpen method is important and missing!

**Comment by hipstersmoothie** [comment]
merging into #959
