### ISSUE TITLE
Set and get individual pixels

### ISSUE THREAD

**Issue by hieyou1** [jimp-dev/jimp#812]
**Is your feature request related to a problem? Please describe.**
Yes, I really need to set and get individual pixels of an image with the project I'm working on.
**Describe the solution you'd like**
I currently am using [ImageJS](https://github.com/guyonroche/imagejs) for this processing, maybe you can find some inspiration there. (Note, the last commit is from 2015).
**Describe alternatives you've considered**
Look above.
**Additional context**
Nothing to say about this.

**Comment by mubaidr** [comment]
I think this is what you need: 
https://github.com/oliver-moran/jimp/tree/master/packages/jimp#low-level-manipulation

```js
image.bitmap.data; // a Buffer of the raw bitmap data
image.bitmap.width; // the width of the image
image.bitmap.height; // the height of the image
```
OR
```js
image.scan(0, 0, image.bitmap.width, image.bitmap.height, function(x, y, idx) {
  // do your stuff..
});
```
