### ISSUE TITLE
Shadow plugin has no effect

### ISSUE THREAD

**Issue by lawrence-witt** [jimp-dev/jimp#813]
# Expected Behavior

Using `.shadow()` on an image will return a new image with the shadow layered underneath.

# Current Behavior

Currently just returns the same image with no shadow.

I have tried adding the shadow then compositing the returned image on top of a larger background, thinking that the shadow might be getting cropped out when I run `.shadow()` by itself, but I'm getting the same result.

The size of the image I'm trying to shadow is 1200 x 713, and 100KB.

I feel like my config might not be set up properly but not really sure where to start - any clarification much appreciated.

## Steps to Reproduce

```
const Jimp = require('jimp');
const shadow = require('@jimp/plugin-shadow');
const configure = require('@jimp/custom');
const myJimp = configure({ plugins: [shadow] }, Jimp);

async function createShadow() {
    const image = await Jimp.read('./inputs/bloodhound.jpg');

    image.shadow({ opacity: 0.8, size: 1.2, blur: 10, x: -75, y: -75 }, (err, image) => {
        if (err) {
            console.log(err);
        } else {
            image.write('./outputs/bloodhound_shadow.jpg');
        }
    })
};

createShadow();
```

## Context

- Jimp Version: 0.8.5
- Operating System: Windows 10
- Node version: v10.16.0

**Comment by lekoaf** [comment]
Are you not getting an error trying this? First of all, you should use `myJimp.read` and `myJimp.shadow()` instead of `Jimp`. And second, the example in the documentation is wrong. There is no `blur` property on the options object.

**Comment by lazarusWist** [comment]
No errors, no, it just writes what appears to be the same file to the new location. Have changed the read function to `myJimp.read()` and get the same result.

I do get a TypeError when running `myJimp.shadow()` as it says it's not a function. I don't understand where I would pass it my image in that case anyway, since myJimp has no knowledge of my image and the shadow function only takes options and a callback?

**Comment by lekoaf** [comment]
Applogies. Of course it’s const img = myJimp.read ...

And then img.shadow().

**Comment by lazarusWist** [comment]
Out of curiosity I installed the circle and fisheye plugins to see if it was something with my config causing the problem and they both work fine. Reinstalled the shadow plugin and played around in the source files for a while but just cannot get it to work.

**Comment by lekoaf** [comment]
Strange, I got it to work just fine yesterday, thanks to you actually. I found this issue while Googling how to use plugins. :)

**Comment by jinseokoh** [comment]
in case you still wonder why the shadow plugin doesn't work, you've gotta use a .png image w/ transparent borders around. just my 2 cents. ;-)

**Comment by lekoaf** [comment]
> in case you still wonder why the shadow plugin doesn't work, you've gotta use a .png image w/ transparent borders around. just my 2 cents. ;-)

Doh! Of course! :smile:
