### ISSUE TITLE
How to save image as gif

### ISSUE THREAD

**Issue by higoka** [jimp-dev/jimp#814]
How can i save an image as a gif?

this doesn't work: 
```js
const Jimp = require('jimp')

const baseImage = new Jimp(100, 100)
baseImage.write('test.gif')
```

using `baseImage.write('test.png')` works just fine as expected

**Comment by csedgwick** [comment]
Having the same issue - gifs write out as empty 0KB files.

**Comment by hipstersmoothie** [comment]
merging into #1000
