### ISSUE TITLE
[Question] How to watermark (composite) the files of an entire directory?

### ISSUE THREAD

**Issue by doncabreraphone** [jimp-dev/jimp#822]
Sorry to not follow the form, but this is a question not a bug or issue report.

How can we watermark (using composite) the files of an entire directory?

This is my working code. Tried ``folder/*.{jpg}`` and every variant, but nothing seems to work, not to lift the file or to export it.

Expected behavior?

To get ``folder/*.jpg``, add the watermark and export the files to ``folder/*-watermark.jpg"

````
var Jimp = require('jimp');

var images = ['./themes/WEP/assets/interviews/img/', './themes/WEP/static/favicon-32x32.png'];


var jimps = [];

for (var i = 0; i < images.length; i++) {
  jimps.push(Jimp.read(images[i]));
}

Promise.all(jimps).then(function(data) {
  return Promise.all(jimps);
}).then(function(data) {
  data[0].composite(data[1],0,0);

  data[0].write('./themes/WEP/assets/interviews/img/', function() {
    console.log("wrote the image");
  });
});
````

**Comment by hipstersmoothie** [comment]
that should work
