### ISSUE TITLE
WebAssembly version for speed.

### ISSUE THREAD

**Issue by intervalia** [jimp-dev/jimp#833]
I was wondering if you were considering making a WebAssembly (WASM) version of your library.

WebAssembly has been in Node since version 8. Your code could run substantially faster if ported to WASM and it would be compatible with all LTS versions of Node

Just a suggestion that could help improve your library.

**Comment by elad-yosifon** [comment]
👍

**Comment by forivall** [comment]
I would recommend porting the code to assemblyscript.

**Comment by forivall** [comment]
WHOOPS i started working on implementing this.

**Comment by ChristianUlbrich** [comment]
Why should a WASM version be significantly faster, than the JavaScript version? Just for context, have a look at: https://colineberhardt.github.io/wasm-mandelbrot/#WebAssembly

Compare the JS version of the Mandelbrot to the AssemblyScript one:
* https://github.com/ColinEberhardt/wasm-mandelbrot/blob/master/js/mandelbrot.js
* https://github.com/ColinEberhardt/wasm-mandelbrot/blob/master/assemblyscript/mandelbrot.ts 

_Simply_ translating code to assemblyscript will not likely give you a speed boost. While assemblyscript claims to have a _optimized native Math implementation_ I could not find any real world numbers.

I do not want to discourage you, but I really doubt your initial statement:
> Your code could run substantially faster if ported to WASM

For context have a look at the following articles:
* https://stackoverflow.com/questions/48173979/why-is-webassembly-function-almost-300-time-slower-than-same-js-function
* http://link.crwd.fr/45ZL#https://blog.acolyer.org/2017/09/18/bringing-the-web-up-to-speed-with-webassembly/?utm_campaign=crowdfire&utm_content=crowdfire&utm_medium=social&utm_source=twitter
* https://discourse.threejs.org/t/porting-three-js-to-webassembly-with-assemblyscript/11629/6

**Comment by hipstersmoothie** [comment]
I've never really used wasm myself. but it seems like the best way to use wasm in jimp would either be through:

- using wasm-ified PNG, JPEG, etc 
- Building a new version of jimp (probably a new project) written on top of `ImageMagick` but `sharp` would probably be the one to do that. 

This could also get ridiculously large and not be suited for browsers anymore

**Comment by forivall** [comment]
@ChristianUlbrich yeah, i read the mandelbrot comparison when i was working on this, and the results i've found has concluded that there isn't a huge amount of speed boost. I'm not actively working on the PR, but it was still worth the investigation.

**Comment by forivall** [comment]
and now i've stumbled onto https://github.com/gpujs/gpu.js and i'm curious if that could give speedups...

**Comment by forivall** [comment]
Additionally, it looks like libvips has been ported to wasm, so that's a definite speedup if we can run things entirely inside of libvips, while preserving the jimp interface https://github.com/kleisauke/wasm-vips

**Comment by sjoerd108** [comment]
Not quite WASM, but I've recently started a project that aims to implement many Jimp functions as a native C++ addon, it can greatly increase server-side image processing: https://github.com/sjoerd108/jimp-native

**Comment by intervalia** [comment]
Nice!!!

**Comment by forivall** [comment]
@sjoerd108 note that, if it's a naiive port, the wasm time and native times may be similar, as I observed here https://github.com/owldotco/damerau-levenshtein/pull/2

**Comment by sjoerd108** [comment]
@forivall I'm aware, and I'm fairly certain a WASM port would get close to native speeds. I want to look into potentially reusing the C++ code written for jimp-native to help with a WASM version, but I haven't looked into it enough to say if that can work as I'm not very familiar with WASM.

**Comment by hipstersmoothie** [comment]
closing in favor of https://github.com/jimp-dev/jimp/issues/1174
