### ISSUE TITLE
Text manipulation in depth

### ISSUE THREAD

**Issue by singhadarsh93** [jimp-dev/jimp#835]
I am using jimp for manipulating text over images ,
I have already figured out some properties in image.print() method but I need more properties like stroke , tracking , leading , rotation , color of text , etc , Can I do all that in Jimp , I need all parameter details of image.print() method .
I have following transformations on text 

`{
            "font": "Verdana",
            "text": "VIDVOCAL",
            "fontSize": 60,
            "fillColor": [
                0.92156994342804,
                0.92156994342804,
                0.92156994342804
            ],
            "applyStroke": false,
            "applyFill": true,
            "justification": 7413,
            "tracking": 0,
            "allCaps": false,
            "fauxBold": false,
            "fauxItalic": false,
            "superscript": false,
            "subscript": false,
            "leading": 72,
            "horizontalScale": 1,
            "fontStyle": "Regular",
            "fontFamily": "Verdana",
                    "position": [
                        281.521339158144,
                        70.1298754789103,
                        0
                    ],
                    "scale": [
                        100,
                        100,
                        100
                    ],
                    "rotation": 0,
                    "opacity": 10,
                    "anchorPointValue": [
                        0,
                        0,
                        0
                    ],
                    "compHeight": 1080,
                    "width": 316.34765625,
                    "height": 45.439453125

}`

Please help me , I am stuck in this

**Comment by hipstersmoothie** [comment]
for color and rotation you could put them in their own jimp then blit it over the original image. as for the more complex options those aren't likely to come
