### ISSUE TITLE
i run the examples of browser, it seems jimp doesn't  support ie11

### ISSUE THREAD

**Issue by birdbirdc** [jimp-dev/jimp#839]
hi,i am a newer in jimp.

i think that jimp is correctly installed  by nodejs.
i want to use jimp in the web.so i run some of examples below.
nodejs\node_modules\npm\node_modules\jimp\browser\examples

it is  correct by edge to open the examples(eg example2.html),the picture is showed,
and  colour is changed to black and white.
But when i use ie11 to open  the examples(eg example2.html),and allow to run the activeX,the picture isn't displayed.

maybe there is something need to be set in ie11,please tell me about it.
or jimp is  not support in ie11?

**Comment by hipstersmoothie** [comment]
jump does not support ie11 (and you shouldn't either!)
