### ISSUE TITLE
Need more example for the CLI

### ISSUE THREAD

**Issue by GabrielDelepine** [jimp-dev/jimp#843]
**Is your feature request related to a problem? Please describe.**
I found very difficult to understand how to use the CLI

**Describe the solution you'd like**
Propose more examples in the README.md will help a lot

**Describe alternatives you've considered**
More example print with `jimp --help`

**Additional context**
My use case : autocrop a PNG from command line

**Comment by hipstersmoothie** [comment]
The cli has been deprecated to focus on making jimp itself better. A cli with a better api can come later
