### ISSUE TITLE
flatten (Removing alpha channel)

### ISSUE THREAD

**Issue by ventr1x** [jimp-dev/jimp#856]
libs like gm, ImageMagick and sharp have the option to flatten the image = removing the alpha channel if any exists.
Am I missing a documented feature that allows this with Jimp (rgba(false) does not work)?

Example use case:
I need to load an image, remove alpha channels, resize it, take its buffer and upload it to a device.
In my specific case I work with macro keys (Streamdeck for example) which expect an exact buffer size for its resolution. Including alpha channel makes the buffer too big.

This feature is needed for many services, even google/ios app stores that don't allow alpha channels on specific images.
Of course I could enforce not using png as a source, but it's still a missing feature and I don't like to limit customers or software because of this.

As sharp takes a fine 60MB hit (and is troublesome with native code for e.g. packing it into an exe or using it on microprocessors), alternatives like Jimp are very welcome but is currently impossible for me to use because of this.

**Comment by tgrajewski** [comment]
If you're saving PNGs, then you can try the `colorType()` method on the image:

```javascript
image.colorType(0);  // Grayscale without alpha
image.colorType(2);  // Truecolor without alpha
```

I'm not Jimp contributor, it's just a thing that I've found out in the docs.
