### ISSUE TITLE
Reduce the number of colors in an image

### ISSUE THREAD

**Issue by jmaferreira** [jimp-dev/jimp#871]
I would like to have a method on Jimp to reduce the number of colors in an image. Similar to what happens when we convert an image from RGB to Indexed color / pallet.

It would be nice to have something like:
```
image.reduceColors(numOfColors)
```

The `RgbQuant.js` library does this, but it uses the canvas to accomplish the same effect.

**Comment by SelfDevTV** [comment]
I second this. Would be so nice to have.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.1.0`](https://github.com/jimp-dev/jimp/releases/tag/v1.1.0) :rocket:
