### ISSUE TITLE
Typescript: compiler errors with type definition 

### ISSUE THREAD

**Issue by kduffie** [jimp-dev/jimp#872]
# Expected Behavior

Recommended typescript import statement should work

# Current Behavior

Error from tsc:  Jimp declared twice

# Failure Information (for bugs)

Here is the compiler output:

error TS2459: Module '"../../../../Users/kduffie/guild-server/node_modules/jimp/types/ts3.1"' declares 'Jimp' locally, but it is not exported.

8 import { Jimp } from 'jimp';
           ~~~~

  node_modules/jimp/types/ts3.1/index.d.ts:42:6
    42 type Jimp = JimpType & IntersectedPluginTypes;
            ~~~~
    'Jimp' is declared here.
  node_modules/jimp/types/ts3.1/index.d.ts:44:15
    44 declare const Jimp: JimpConstructors & IntersectedPluginConsts & {
                     ~~~~
    and here.

## Steps to Reproduce

node project in vscode with typescript 3.8.3
npm install --save jimp
tsc -p tsconfig.json

tsconfig.json includes allowSyntheticDefaultImports=true

## Context
- Jimp Version: 0.10.1
- Operating System: MacOS
- Node version: 10.16.1
- Typescript: 3.8.3
- vscode: 1.43.2

## Failure Logs

**Comment by hipstersmoothie** [comment]
This should be good now or fixed by incoming ts rewrite
