### ISSUE TITLE
Error: Unsupported MIME type: image/gif

### ISSUE THREAD

**Issue by qburst-varunnath** [jimp-dev/jimp#883]
I am getting the below error while trying to resize a gif image, for other types it is working fine.

Error: Unsupported MIME type: image/gif

# Expected Behavior

The image should be resized without any error

# Current Behavior

Getting the below error message:
Error: Unsupported MIME type: image/gif

## Steps to Reproduce
- Execute resize method
- Getting the above error

**Screenshots**

## Context

- Jimp Version: 0.6.4
- Operating System: Ubuntu 18.04
- Node version: 10.17.0

## Failure Logs

Error: Unsupported MIME type: image/gif

**Comment by hipstersmoothie** [comment]
merging into #948
