### ISSUE TITLE
loadfont changes input path format

### ISSUE THREAD

**Issue by moeinrahimi** [jimp-dev/jimp#894]
loading custom font with loadFont function,
I pass vazir.fnt but loadfunction is looking for vazir.png file!

load custom font 

# Current Behavior

load font path arg is gets changed.

# Failure Information (for bugs)
```
(node:47432) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'E:\projects\jim-halpert\font.png'
```
## Steps to Reproduce
```
 const Jimp = require('jimp')
 const path =require('path')
  let fPath = path.resolve(__dirname,'vazir.fnt')
  console.log("fPath", fPath)
  let font = await Jimp.loadFont(fPath);
```
IF YOUR ISSUE DEPENDS ON A PARTICULAR IMAGE BE SURE TO INCLUDE THIS AS WELL. WE CAN'T REPORDUCE IF WE DON'T HAVE YOUR IMAGE

1. step 1
2. step 2
3. you get it... -->

**Screenshots**

## Context

- Jimp Version: jimp@0.12.1
- Operating System: windows 10
- Node version: 12.16.0

(node:47432) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'E:\projects\jim-halpert\font.png'

**Comment by Raggok** [comment]
fnt files need a png file to work, always comes with 1 or more png files.
