### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [jimp-dev/jimp#895]
# Expected Behavior

I can clone the repo, install the dependencies and run tests as it is described [here](https://github.com/oliver-moran/jimp/blob/master/CONTRIBUTING.md).

# Current Behavior

Tests can't be run.

# Failure Information (for bugs)

```
Error: Cannot find module '/home/sh4dow/tmp/jimp/node_modules/@jimp/test-utils/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

## Steps to Reproduce

1. `git clone git@github.com:oliver-moran/jimp.git`
2. `yarn`
3. `yarn test`

## Context

- Jimp Version: current master
- Operating System: Mint 19.3
- Node version: v12.16.2
- yarn version: 1.22.4

**Comment by hipstersmoothie** [comment]
Test run fine now
