### ISSUE TITLE
yarn clean:build or any command that depends on it fails on Windows

### ISSUE THREAD

**Issue by tgrajewski** [jimp-dev/jimp#910]
# Expected Behavior

`yarn clean:build` shouldn't fail or any command that depends on it (like `yarn build`).

# Current Behavior

`yarn clean:build` or any other command that depends on it fails.

# Failure Information (for bugs)

There is no `rm` command on Windows obviously. What should a Windows user do if he/she wants to contribute to this project? Maybe CONTRIBUTING.md should be updated with more details?

## Steps to Reproduce

1. Clone this repository
2. Run `npm install`
3. Run `yarn build` or `yarn clean:build` or `npm run build` or `npm run clean:build`, etc.

## Context

- Jimp Version: 0.14
- Operating System: Windows 10
- Node version: 12

## Failure Logs

```
'rm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by AndreasWJ** [comment]
Running `yarn build` works on Windows with Git Bash rather than CMD.

Although, I'm running into other issues, might be unrelated though.
