### ISSUE TITLE
error on installing jimp

### ISSUE THREAD

**Issue by Reubencfernandes** [jimp-dev/jimp#925]
# Current Behavior
when i install jimp i get Unexpected end of JSON input while parsing near '...4,"npm-signature":"--'

## Steps to Reproduce

![Screenshot_2](https://user-images.githubusercontent.com/31587917/89864232-3a39d700-dbc9-11ea-8476-015768c45acb.png)

**Screenshots**

## Context

- Jimp Version: 0.16.0
- Operating System: windows 10
- Node version: v12.18.0

## Failure Logs
```npm ERR! Unexpected end of JSON input while parsing near '...4,"npm-signature":"--'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-08-11T06_19_50_794Z-debug.log```

[2020-08-11T06_28_03_416Z-debug.log](https://github.com/oliver-moran/jimp/files/5055161/2020-08-11T06_28_03_416Z-debug.log)

**Comment by hipstersmoothie** [comment]
pretty sure it installs fine. if this is still happening please open another issue
