### ISSUE TITLE
Missing repo information on NPM

### ISSUE THREAD

**Issue by dandv** [jimp-dev/jimp#927]
# Expected Behavior

I noticed this package was installed as an indirect dependency of Gatsby, and seemed to carry some extraneous files ([separate issue](https://github.com/oliver-moran/jimp/issues/928)). At https://www.npmjs.com/package/@jimp/bmp I'd expect to see a link to this repo, and possibly some more information about the package.

# Current Behavior

![image](https://user-images.githubusercontent.com/33569/90500223-72787280-e0ff-11ea-9d1f-2d3459eabf47.png)

**Comment by hipstersmoothie** [comment]
This has been fixed
