### ISSUE TITLE
Reading a FileStream into jimp buffer

### ISSUE THREAD

**Issue by AdamBD** [jimp-dev/jimp#943]
This is a question not an issue etc.

I have a web application where users can upload an image to my server for storage. I would like to add a watermark to these images before saving them.

I am using a library called multers3 which takes an image file and easily uploads it to S3 like storage.

When the image is held by multers3 it is in a `FileStream`. I am trying to read this filestream into a buffer so that I can then pass it to jimp.

Is jimp able to take FileStream directly, and if not is there any advice on converting a filestream into a buffer?

**Comment by hipstersmoothie** [comment]
I don't think so
