### ISSUE TITLE
Error installing on windows

### ISSUE THREAD

**Issue by juandavidaa** [jimp-dev/jimp#944]
# Expected Behavior

a normal intallation of Jimp

# Current Behavior

trying to install Jimp on windows 10 I get this error:

Unexpected end of JSON input while parsing near '...anary.792.339.0"},"pe'

## Steps to Reproduce

1. step 1 npm i jimp
2. you get it... --> npm ERR! Unexpected end of JSON input while parsing near '...anary.792.339.0"},"pe'

**Screenshots**
![image](https://user-images.githubusercontent.com/12754797/94704800-ea90a580-0305-11eb-8de8-de0e28eec65a.png)

## Context

- Jimp Version: 0.16.1
- Operating System: windows 10 64 bits
- Node version: 12.18.4

## Failure Logs

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'jimp'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose npm-session e39b8366649e39ce
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/jimp 406ms (from cache)
8 silly pacote tag manifest for jimp@latest fetched in 428ms
9 timing stage:loadCurrentTree Completed in 677ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 73ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule jimp@0.16.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 114ms (from cache)
18 silly pacote range manifest for @babel/runtime@^7.7.2 fetched in 119ms
19 silly resolveWithNewModule @babel/runtime@7.11.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 267ms (from cache)
21 silly pacote range manifest for regenerator-runtime@^0.13.3 fetched in 273ms
22 silly resolveWithNewModule regenerator-runtime@0.13.7 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/@jimp%2fcustom 281ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugins 285ms (from cache)
25 silly pacote range manifest for @jimp/custom@^0.16.1 fetched in 289ms
26 silly resolveWithNewModule @jimp/custom@0.16.1 checking installable status
27 silly pacote range manifest for @jimp/plugins@^0.16.1 fetched in 291ms
28 silly resolveWithNewModule @jimp/plugins@0.16.1 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/@jimp%2ftypes 291ms (from cache)
30 silly pacote range manifest for @jimp/types@^0.16.1 fetched in 297ms
31 silly resolveWithNewModule @jimp/types@0.16.1 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/@jimp%2fcore 91ms (from cache)
33 silly pacote range manifest for @jimp/core@^0.16.1 fetched in 94ms
34 silly resolveWithNewModule @jimp/core@0.16.1 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/buffer 117ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/any-base 118ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/exif-parser 118ms (from cache)
38 silly pacote range manifest for buffer@^5.2.0 fetched in 120ms
39 silly resolveWithNewModule buffer@5.6.0 checking installable status
40 http fetch GET 304 https://registry.npmjs.org/@jimp%2futils 121ms (from cache)
41 silly pacote range manifest for any-base@^1.1.0 fetched in 123ms
42 silly resolveWithNewModule any-base@1.1.0 checking installable status
43 silly pacote range manifest for exif-parser@^0.1.12 fetched in 124ms
44 silly resolveWithNewModule exif-parser@0.1.12 checking installable status
45 silly pacote range manifest for @jimp/utils@^0.16.1 fetched in 124ms
46 silly resolveWithNewModule @jimp/utils@0.16.1 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/file-type 170ms (from cache)
48 silly pacote range manifest for file-type@^9.0.0 fetched in 181ms
49 silly resolveWithNewModule file-type@9.0.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/load-bmfont 213ms (from cache)
51 silly pacote range manifest for load-bmfont@^1.3.1 fetched in 215ms
52 silly resolveWithNewModule load-bmfont@1.4.1 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/pixelmatch 227ms (from cache)
54 silly pacote range manifest for pixelmatch@^4.0.2 fetched in 230ms
55 silly resolveWithNewModule pixelmatch@4.0.2 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/phin 234ms (from cache)
57 silly pacote range manifest for phin@^2.9.1 fetched in 237ms
58 silly resolveWithNewModule phin@2.9.3 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/tinycolor2 237ms (from cache)
60 silly pacote range manifest for tinycolor2@^1.4.1 fetched in 240ms
61 silly resolveWithNewModule tinycolor2@1.4.2 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/ieee754 84ms (from cache)
63 http fetch GET 304 https://registry.npmjs.org/base64-js 85ms (from cache)
64 silly pacote range manifest for ieee754@^1.1.4 fetched in 86ms
65 silly resolveWithNewModule ieee754@1.1.13 checking installable status
66 silly pacote range manifest for base64-js@^1.0.2 fetched in 87ms
67 silly resolveWithNewModule base64-js@1.3.1 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/parse-bmfont-ascii 101ms (from cache)
69 silly pacote range manifest for parse-bmfont-ascii@^1.0.3 fetched in 108ms
70 silly resolveWithNewModule parse-bmfont-ascii@1.0.6 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/xtend 114ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/parse-bmfont-xml 119ms (from cache)
73 silly pacote range manifest for xtend@^4.0.0 fetched in 120ms
74 silly resolveWithNewModule xtend@4.0.2 checking installable status
75 silly pacote range manifest for parse-bmfont-xml@^1.1.4 fetched in 124ms
76 silly resolveWithNewModule parse-bmfont-xml@1.1.4 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/xhr 128ms (from cache)
78 http fetch GET 304 https://registry.npmjs.org/parse-bmfont-binary 130ms (from cache)
79 silly pacote range manifest for xhr@^2.0.1 fetched in 133ms
80 silly resolveWithNewModule xhr@2.5.0 checking installable status
81 silly pacote range manifest for parse-bmfont-binary@^1.0.5 fetched in 135ms
82 silly resolveWithNewModule parse-bmfont-binary@1.0.6 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/mime 136ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/buffer-equal 140ms (from cache)
85 silly pacote range manifest for mime@^1.3.4 fetched in 140ms
86 silly resolveWithNewModule mime@1.6.0 checking installable status
87 silly pacote version manifest for buffer-equal@0.0.1 fetched in 144ms
88 silly resolveWithNewModule buffer-equal@0.0.1 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/xml-parse-from-string 79ms (from cache)
90 silly pacote range manifest for xml-parse-from-string@^1.0.0 fetched in 81ms
91 silly resolveWithNewModule xml-parse-from-string@1.0.1 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/xml2js 99ms (from cache)
93 silly pacote range manifest for xml2js@^0.4.5 fetched in 106ms
94 silly resolveWithNewModule xml2js@0.4.23 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/xmlbuilder 81ms (from cache)
96 silly pacote range manifest for xmlbuilder@~11.0.0 fetched in 84ms
97 silly resolveWithNewModule xmlbuilder@11.0.1 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/sax 85ms (from cache)
99 silly pacote range manifest for sax@>=0.6.0 fetched in 87ms
100 silly resolveWithNewModule sax@1.2.4 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/parse-headers 88ms (from cache)
102 http fetch GET 304 https://registry.npmjs.org/global 89ms (from cache)
103 silly pacote range manifest for parse-headers@^2.0.0 fetched in 90ms
104 silly resolveWithNewModule parse-headers@2.0.3 checking installable status
105 silly pacote range manifest for global@~4.3.0 fetched in 91ms
106 silly resolveWithNewModule global@4.3.2 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/is-function 333ms (from cache)
108 silly pacote range manifest for is-function@^1.0.1 fetched in 335ms
109 silly resolveWithNewModule is-function@1.0.2 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/process 84ms (from cache)
111 http fetch GET 304 https://registry.npmjs.org/min-document 86ms (from cache)
112 silly pacote range manifest for process@~0.5.1 fetched in 86ms
113 silly resolveWithNewModule process@0.5.2 checking installable status
114 silly pacote range manifest for min-document@^2.19.0 fetched in 88ms
115 silly resolveWithNewModule min-document@2.19.0 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/dom-walk 85ms (from cache)
117 silly pacote range manifest for dom-walk@^0.1.0 fetched in 87ms
118 silly resolveWithNewModule dom-walk@0.1.2 checking installable status
119 http fetch GET 304 https://registry.npmjs.org/pngjs 80ms (from cache)
120 silly pacote range manifest for pngjs@^3.0.0 fetched in 88ms
121 silly resolveWithNewModule pngjs@3.4.0 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-displace 111ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-dither 116ms (from cache)
124 silly pacote range manifest for @jimp/plugin-displace@^0.16.1 fetched in 119ms
125 silly resolveWithNewModule @jimp/plugin-displace@0.16.1 checking installable status
126 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-crop 121ms (from cache)
127 silly fetchPackageMetaData error for @jimp/plugin-crop@^0.16.1 Unexpected end of JSON input while parsing near '...anary.792.339.0"},"pe'
128 silly pacote range manifest for @jimp/plugin-dither@^0.16.1 fetched in 125ms
129 silly resolveWithNewModule @jimp/plugin-dither@0.16.1 checking installable status
130 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-blur 148ms (from cache)
131 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-circle 151ms (from cache)
132 silly pacote range manifest for @jimp/plugin-blur@^0.16.1 fetched in 159ms
133 silly resolveWithNewModule @jimp/plugin-blur@0.16.1 checking installable status
134 silly pacote range manifest for @jimp/plugin-circle@^0.16.1 fetched in 164ms
135 silly resolveWithNewModule @jimp/plugin-circle@0.16.1 checking installable status
136 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-contain 175ms (from cache)
137 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-color 187ms (from cache)
138 silly pacote range manifest for @jimp/plugin-contain@^0.16.1 fetched in 191ms
139 silly resolveWithNewModule @jimp/plugin-contain@0.16.1 checking installable status
140 silly pacote range manifest for @jimp/plugin-color@^0.16.1 fetched in 199ms
141 silly resolveWithNewModule @jimp/plugin-color@0.16.1 checking installable status
142 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-cover 202ms (from cache)
143 silly pacote range manifest for @jimp/plugin-cover@^0.16.1 fetched in 215ms
144 silly resolveWithNewModule @jimp/plugin-cover@0.16.1 checking installable status
145 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-blit 238ms (from cache)
146 silly pacote range manifest for @jimp/plugin-blit@^0.16.1 fetched in 250ms
147 silly resolveWithNewModule @jimp/plugin-blit@0.16.1 checking installable status
148 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-flip 147ms (from cache)
149 silly pacote range manifest for @jimp/plugin-flip@^0.16.1 fetched in 152ms
150 silly resolveWithNewModule @jimp/plugin-flip@0.16.1 checking installable status
151 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-fisheye 276ms (from cache)
152 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-gaussian 155ms (from cache)
153 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-invert 154ms (from cache)
154 silly pacote range manifest for @jimp/plugin-fisheye@^0.16.1 fetched in 284ms
155 silly resolveWithNewModule @jimp/plugin-fisheye@0.16.1 checking installable status
156 silly pacote range manifest for @jimp/plugin-gaussian@^0.16.1 fetched in 164ms
157 silly resolveWithNewModule @jimp/plugin-gaussian@0.16.1 checking installable status
158 silly pacote range manifest for @jimp/plugin-invert@^0.16.1 fetched in 163ms
159 silly resolveWithNewModule @jimp/plugin-invert@0.16.1 checking installable status
160 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-normalize 131ms (from cache)
161 silly pacote range manifest for @jimp/plugin-normalize@^0.16.1 fetched in 145ms
162 silly resolveWithNewModule @jimp/plugin-normalize@0.16.1 checking installable status
163 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-print 129ms (from cache)
164 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-resize 124ms (from cache)
165 silly pacote range manifest for @jimp/plugin-print@^0.16.1 fetched in 141ms
166 silly resolveWithNewModule @jimp/plugin-print@0.16.1 checking installable status
167 silly pacote range manifest for @jimp/plugin-resize@^0.16.1 fetched in 135ms
168 silly resolveWithNewModule @jimp/plugin-resize@0.16.1 checking installable status
169 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-mask 183ms (from cache)
170 silly pacote range manifest for @jimp/plugin-mask@^0.16.1 fetched in 191ms
171 silly resolveWithNewModule @jimp/plugin-mask@0.16.1 checking installable status
172 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-rotate 137ms (from cache)
173 silly pacote range manifest for @jimp/plugin-rotate@^0.16.1 fetched in 142ms
174 silly resolveWithNewModule @jimp/plugin-rotate@0.16.1 checking installable status
175 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-scale 114ms (from cache)
176 silly pacote range manifest for @jimp/plugin-scale@^0.16.1 fetched in 117ms
177 silly resolveWithNewModule @jimp/plugin-scale@0.16.1 checking installable status
178 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-shadow 98ms (from cache)
179 silly pacote range manifest for @jimp/plugin-shadow@^0.16.1 fetched in 104ms
180 silly resolveWithNewModule @jimp/plugin-shadow@0.16.1 checking installable status
181 http fetch GET 304 https://registry.npmjs.org/timm 113ms (from cache)
182 http fetch GET 304 https://registry.npmjs.org/@jimp%2fplugin-threshold 121ms (from cache)
183 silly pacote range manifest for timm@^1.6.1 fetched in 127ms
184 silly resolveWithNewModule timm@1.7.1 checking installable status
185 silly pacote range manifest for @jimp/plugin-threshold@^0.16.1 fetched in 132ms
186 silly resolveWithNewModule @jimp/plugin-threshold@0.16.1 checking installable status
187 timing stage:rollbackFailedOptional Completed in 1ms
188 timing stage:runTopLevelLifecycles Completed in 2876ms
189 silly saveTree project@1.0.0
189 silly saveTree +-- electron@9.1.0
189 silly saveTree | +-- @electron/get@1.12.2
189 silly saveTree | | +-- debug@4.1.1
189 silly saveTree | | | `-- ms@2.1.2
189 silly saveTree | | +-- env-paths@2.2.0
189 silly saveTree | | +-- fs-extra@8.1.0
189 silly saveTree | | | +-- graceful-fs@4.2.4
189 silly saveTree | | | +-- jsonfile@4.0.0
189 silly saveTree | | | `-- universalify@0.1.2
189 silly saveTree | | +-- global-agent@2.1.12
189 silly saveTree | | | +-- boolean@3.0.1
189 silly saveTree | | | +-- core-js@3.6.5
189 silly saveTree | | | +-- es6-error@4.1.1
189 silly saveTree | | | +-- matcher@3.0.0
189 silly saveTree | | | | `-- escape-string-regexp@4.0.0
189 silly saveTree | | | +-- roarr@2.15.3
189 silly saveTree | | | | +-- detect-node@2.0.4
189 silly saveTree | | | | +-- globalthis@1.0.1
189 silly saveTree | | | | | `-- define-properties@1.1.3
189 silly saveTree | | | | |   `-- object-keys@1.1.1
189 silly saveTree | | | | +-- json-stringify-safe@5.0.1
189 silly saveTree | | | | +-- semver-compare@1.0.0
189 silly saveTree | | | | `-- sprintf-js@1.1.2
189 silly saveTree | | | +-- semver@7.3.2
189 silly saveTree | | | `-- serialize-error@7.0.1
189 silly saveTree | | |   `-- type-fest@0.13.1
189 silly saveTree | | +-- global-tunnel-ng@2.7.1
189 silly saveTree | | | +-- encodeurl@1.0.2
189 silly saveTree | | | +-- lodash@4.17.19
189 silly saveTree | | | +-- npm-conf@1.1.3
189 silly saveTree | | | | +-- config-chain@1.1.12
189 silly saveTree | | | | | +-- ini@1.3.5
189 silly saveTree | | | | | `-- proto-list@1.2.4
189 silly saveTree | | | | `-- pify@3.0.0
189 silly saveTree | | | `-- tunnel@0.0.6
189 silly saveTree | | +-- got@9.6.0
189 silly saveTree | | | +-- @sindresorhus/is@0.14.0
189 silly saveTree | | | +-- @szmarczak/http-timer@1.1.2
189 silly saveTree | | | | `-- defer-to-connect@1.1.3
189 silly saveTree | | | +-- cacheable-request@6.1.0
189 silly saveTree | | | | +-- clone-response@1.0.2
189 silly saveTree | | | | | `-- mimic-response@1.0.1
189 silly saveTree | | | | +-- get-stream@5.1.0
189 silly saveTree | | | | | `-- pump@3.0.0
189 silly saveTree | | | | |   +-- end-of-stream@1.4.4
189 silly saveTree | | | | |   | `-- once@1.4.0
189 silly saveTree | | | | |   |   `-- wrappy@1.0.2
189 silly saveTree | | | | |   `-- once@1.4.0
189 silly saveTree | | | | +-- http-cache-semantics@4.1.0
189 silly saveTree | | | | +-- keyv@3.1.0
189 silly saveTree | | | | | `-- json-buffer@3.0.0
189 silly saveTree | | | | +-- lowercase-keys@2.0.0
189 silly saveTree | | | | +-- normalize-url@4.5.0
189 silly saveTree | | | | `-- responselike@1.0.2
189 silly saveTree | | | |   `-- lowercase-keys@1.0.1
189 silly saveTree | | | +-- decompress-response@3.3.0
189 silly saveTree | | | +-- duplexer3@0.1.4
189 silly saveTree | | | +-- get-stream@4.1.0
189 silly saveTree | | | +-- lowercase-keys@1.0.1
189 silly saveTree | | | +-- mimic-response@1.0.1
189 silly saveTree | | | +-- p-cancelable@1.1.0
189 silly saveTree | | | +-- to-readable-stream@1.0.0
189 silly saveTree | | | `-- url-parse-lax@3.0.0
189 silly saveTree | | |   `-- prepend-http@2.0.0
189 silly saveTree | | +-- progress@2.0.3
189 silly saveTree | | +-- sanitize-filename@1.6.3
189 silly saveTree | | | `-- truncate-utf8-bytes@1.0.2
189 silly saveTree | | |   `-- utf8-byte-length@1.0.4
189 silly saveTree | | `-- sumchecker@3.0.1
189 silly saveTree | +-- @types/node@12.12.50
189 silly saveTree | `-- extract-zip@1.7.0
189 silly saveTree |   +-- concat-stream@1.6.2
189 silly saveTree |   | +-- buffer-from@1.1.1
189 silly saveTree |   | +-- inherits@2.0.4
189 silly saveTree |   | +-- readable-stream@2.3.7
189 silly saveTree |   | | +-- core-util-is@1.0.2
189 silly saveTree |   | | +-- isarray@1.0.0
189 silly saveTree |   | | +-- process-nextick-args@2.0.1
189 silly saveTree |   | | +-- safe-buffer@5.1.2
189 silly saveTree |   | | +-- string_decoder@1.1.1
189 silly saveTree |   | | `-- util-deprecate@1.0.2
189 silly saveTree |   | `-- typedarray@0.0.6
189 silly saveTree |   +-- debug@2.6.9
189 silly saveTree |   | `-- ms@2.0.0
189 silly saveTree |   +-- mkdirp@0.5.5
189 silly saveTree |   | `-- minimist@1.2.5
189 silly saveTree |   `-- yauzl@2.10.0
189 silly saveTree |     +-- buffer-crc32@0.2.13
189 silly saveTree |     `-- fd-slicer@1.1.0
189 silly saveTree |       `-- pend@1.2.0
189 silly saveTree `-- jimp@0.16.1
189 silly saveTree   +-- @babel/runtime@7.11.2
189 silly saveTree   | `-- regenerator-runtime@0.13.7
189 silly saveTree   +-- @jimp/custom@0.16.1
189 silly saveTree   | `-- @jimp/core@0.16.1
189 silly saveTree   |   +-- @jimp/utils@0.16.1
189 silly saveTree   |   +-- any-base@1.1.0
189 silly saveTree   |   +-- buffer@5.6.0
189 silly saveTree   |   | +-- base64-js@1.3.1
189 silly saveTree   |   | `-- ieee754@1.1.13
189 silly saveTree   |   +-- exif-parser@0.1.12
189 silly saveTree   |   +-- file-type@9.0.0
189 silly saveTree   |   +-- load-bmfont@1.4.1
189 silly saveTree   |   | +-- buffer-equal@0.0.1
189 silly saveTree   |   | +-- mime@1.6.0
189 silly saveTree   |   | +-- parse-bmfont-ascii@1.0.6
189 silly saveTree   |   | +-- parse-bmfont-binary@1.0.6
189 silly saveTree   |   | +-- parse-bmfont-xml@1.1.4
189 silly saveTree   |   | | +-- xml-parse-from-string@1.0.1
189 silly saveTree   |   | | `-- xml2js@0.4.23
189 silly saveTree   |   | |   +-- sax@1.2.4
189 silly saveTree   |   | |   `-- xmlbuilder@11.0.1
189 silly saveTree   |   | +-- phin@2.9.3
189 silly saveTree   |   | +-- xhr@2.5.0
189 silly saveTree   |   | | +-- global@4.3.2
189 silly saveTree   |   | | | +-- min-document@2.19.0
189 silly saveTree   |   | | | | `-- dom-walk@0.1.2
189 silly saveTree   |   | | | `-- process@0.5.2
189 silly saveTree   |   | | +-- is-function@1.0.2
189 silly saveTree   |   | | +-- parse-headers@2.0.3
189 silly saveTree   |   | | `-- xtend@4.0.2
189 silly saveTree   |   | `-- xtend@4.0.2
189 silly saveTree   |   +-- phin@2.9.3
189 silly saveTree   |   +-- pixelmatch@4.0.2
189 silly saveTree   |   | `-- pngjs@3.4.0
189 silly saveTree   |   `-- tinycolor2@1.4.2
189 silly saveTree   +-- @jimp/plugins@0.16.1
189 silly saveTree   | +-- @jimp/plugin-blit@0.16.1
189 silly saveTree   | +-- @jimp/plugin-blur@0.16.1
189 silly saveTree   | +-- @jimp/plugin-circle@0.16.1
189 silly saveTree   | +-- @jimp/plugin-color@0.16.1
189 silly saveTree   | +-- @jimp/plugin-contain@0.16.1
189 silly saveTree   | +-- @jimp/plugin-cover@0.16.1
189 silly saveTree   | +-- @jimp/plugin-displace@0.16.1
189 silly saveTree   | +-- @jimp/plugin-dither@0.16.1
189 silly saveTree   | +-- @jimp/plugin-fisheye@0.16.1
189 silly saveTree   | +-- @jimp/plugin-flip@0.16.1
189 silly saveTree   | +-- @jimp/plugin-gaussian@0.16.1
189 silly saveTree   | +-- @jimp/plugin-invert@0.16.1
189 silly saveTree   | +-- @jimp/plugin-mask@0.16.1
189 silly saveTree   | +-- @jimp/plugin-normalize@0.16.1
189 silly saveTree   | +-- @jimp/plugin-print@0.16.1
189 silly saveTree   | +-- @jimp/plugin-resize@0.16.1
189 silly saveTree   | +-- @jimp/plugin-rotate@0.16.1
189 silly saveTree   | +-- @jimp/plugin-scale@0.16.1
189 silly saveTree   | +-- @jimp/plugin-shadow@0.16.1
189 silly saveTree   | +-- @jimp/plugin-threshold@0.16.1
189 silly saveTree   | `-- timm@1.7.1
189 silly saveTree   +-- @jimp/types@0.16.1
189 silly saveTree   `-- regenerator-runtime@0.13.7
190 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...anary.792.339.0"},"pe'
190 verbose stack     at JSON.parse (<anonymous>)
190 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
190 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
190 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
191 verbose cwd C:\Users\jdaa3\Desktop\Project
192 verbose Windows_NT 10.0.18363
193 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "jimp"
194 verbose node v12.18.4
195 verbose npm  v6.14.6
196 error Unexpected end of JSON input while parsing near '...anary.792.339.0"},"pe'
197 verbose exit [ 1, true ]
`

**Comment by hipstersmoothie** [comment]
I don't think this is an issue anymore. if it is feel free to re open this issue
