### ISSUE TITLE
QUESTION - Can someone provide a sample set of images for the .mask API?

### ISSUE THREAD

**Issue by AdamBD** [jimp-dev/jimp#949]
Hello,

I am trying to use the mask method of this lib but I cannot successfully implement it with consistent results. It seems I do not really understand how the mask function itself is working.

Could anyone provide two sample images and an explanation of how this function is working to understand better how to create a mask to achieve the results I'm looking for?

Thanks!

**Comment by vunguyen105** [comment]
Hello
You prepare 2 photos, the photo to have the part to mask is black, I have done and succeeded
