### ISSUE TITLE
Altered colored just by opening a source image

### ISSUE THREAD

**Issue by Tyki** [jimp-dev/jimp#952]
# Expected Behavior

The colors should be remains the same

# Current Behavior

Colors are altered (red being darker for instance)

# Failure Information (for bugs)

## Steps to Reproduce

`
let original = await Jimp.read('url')
    return original.getBufferAsync(original.getMIME())
`

I get a Buffer and re-upload it to Contentful. You can see in the screenshot that the original image, just opened to get the buffer became darker

**Screenshots**

<img width="297" alt="Capture d’écran 2020-10-08 à 15 13 11" src="https://user-images.githubusercontent.com/2605688/95463321-e9e8b680-0978-11eb-9342-97f1c85988af.png">

## Context

We are using Jimp to add a Play button icon to the origin image. Our customer showed us that the image became darker after processing the composite. After investigation, it's not about composite but just opening the image itself.

- Jimp Version: 0.6.0 in production. 0.16.1 tested to fix the issue
- Operating System: AWS Serverless 
- Node version: 12.16

**Comment by hipstersmoothie** [comment]
This is just a fact of life with the js codecs. Switching to the wasm codecs might fix this
