### ISSUE TITLE
mime typing should be string | -1 instead of string

### ISSUE THREAD

**Issue by Newbie012** [jimp-dev/jimp#960]
Can't use `Jimp.AUTO` on typescript as mime type since it's typed as a string argument -

![image](https://user-images.githubusercontent.com/10504365/98819023-0626ba00-2435-11eb-8a6c-2e1ab3c50d34.png)

The buggy line -

https://github.com/oliver-moran/jimp/blob/8eb2e9b8dbb2f1cf7c4a4d0da5d2a3436eb83543/packages/jimp/types/index.d.ts#L133

Should be instead:

```
 getBase64(mime: string | Jimp.AUTO, cb: GenericCallback<string, any, this>): this;

// or
 getBase64(mime: string | -1, cb: GenericCallback<string, any, this>): this;

// or
 getBase64(mime: string | number, cb: GenericCallback<string, any, this>): this;
```

**Comment by hipstersmoothie** [comment]
This was fixed
