### ISSUE TITLE
Estimate image size before conversion

### ISSUE THREAD

**Issue by markb-trustifi** [jimp-dev/jimp#966]
I'm using Jimp library to compress images:
```
let image = await Jimp.read(buffer);
buffer = await image.scale(X).quality(Y).getBufferAsync(Z ? Jimp.MIME_PNG:Jimp.MIME_JPEG);
```

Is it possible to predict the final image size without executing the real conversion flow?
There are sites like https://toolstud.io/photo/filesize.php, 
but I need to estimate the image size as strict as possible including all X,Y,Z parameters.

**Comment by hipstersmoothie** [comment]
no the libraries we use don't support that
