### ISSUE TITLE
'request' package needs to be replaced

### ISSUE THREAD

**Issue by anushreemjoshi** [jimp-dev/jimp#970]
Bug Description
Replace 'request' package since it is deprecated.

1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Security issue is reported for http-signature package that is used in 'request' package which is already deprecated.
Request to please replace 'request' package since it is deprecated.

2. What you expected to happen
Update with another suitable package.

3. What actually happened
'request' package is still used.

Environment details
Node.js version
> 12.6.0

**Comment by hipstersmoothie** [comment]
request is not longer used
