### ISSUE TITLE
Get Warning: React does not recognize the `maskType` prop on a DOM element error in the console

### ISSUE THREAD

**Issue by jamespfarrell** [jimp-dev/jimp#983]
# Expected Behavior

No errors in the console.

# Current Behavior

I have this error in the console:

```
index.js:2177 Warning: React does not recognize the `maskType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `masktype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in mask (created by A)
    in svg (created by A)
    in A (at InfoSection.js:99)
    in div (created by Context.Consumer)
    in Styled(div) (created by Context.Consumer)
    in EmotionCssPropInternal (at InfoSection.js:98)
    in div (created by Context.Consumer)
    in Styled(div) (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in EmotionCssPropInternal (at InfoSection.js:94)
    in div (created by Context.Consumer)
    in Styled(div) (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in Main (created by Context.Consumer)
    in EmotionCssPropInternal (at InfoSection.js:40)
    in InfoSection (at pages/index.js:26)
    in IndexContent (at pages/index.js:44)
    in main (at layout.js:184)
```

# Failure Information (for bugs)

## Steps to Reproduce

Gatsby app with:
import DecoratorAltruistic from '../../images/svg/general/decorators/a.svg'
....

return (
 <DecoratorAltruistic />
)

**Screenshots**

![image](https://user-images.githubusercontent.com/10499048/105086946-09c06800-5a9a-11eb-95dc-0c7e610e5b8e.png)

## Context

- Jimp Version: 0.14.0
- "requires": {
        "@babel/runtime": "^7.7.2",
        "@jimp/custom": "^0.14.0",
        "@jimp/plugins": "^0.14.0",
        "@jimp/types": "^0.14.0",
        "regenerator-runtime": "^0.13.3"
      }
- Operating System: macos

**Comment by jamespfarrell** [comment]
It appears to used by gatsby-plugin-sharp:
![image](https://user-images.githubusercontent.com/10499048/105087186-66bc1e00-5a9a-11eb-8260-ea0af8dcd9d2.png)

**Comment by robmarshall** [comment]
@jamespfarrell Did you get anywhere with this? I have come across this issue as well.

**Comment by animeshgarai09** [comment]
![image](https://user-images.githubusercontent.com/24646850/126046321-924f5422-497d-4778-bd33-a1c93c0c7c9b.png)

Facing the issue while importing an SVG.

**Comment by loekTheDreamer** [comment]
I had the exact same issue.

Not sure if it will work out for everyone but just remove the field completely. With my design, it didn't seem to have an effect on the display at all. Maybe its metadata that react just ignores or doesn't even need.

**Comment by brada1703** [comment]
Does anyone else have a fix for this? I tried @loekTheDreamer 's idea, but even with removing "mask-type", I still get the same error.

**Comment by hipstersmoothie** [comment]
This has nothing to do with jimp and is a react error
