### ISSUE TITLE
Image `saturate` / `desaturate` appear on the doc, but not on the module...

### ISSUE THREAD

**Issue by mlbonniec** [jimp-dev/jimp#987]
# Expected Behavior
Hi, I would like to reduce or increase my image saturation, as specified in the doc [here](https://github.com/oliver-moran/jimp/tree/master/packages/jimp#advanced-usage), but the module doesn't have those options.  
My issue refer to another one, previously closed: https://github.com/oliver-moran/jimp/issues/968

# Current Behavior
`Type '"saturate"' is not assignable to type 'ColorActionName'.` because `saturate` or `desaturate` (and `lighten`, `darken`) doesn't exist on `ColorActionName`.

# Failure Information (for bugs)

\-\-\-

## Steps to Reproduce
Try to change the saturation of an image
```js
image.color([{ apply: 'saturate', params: [10] }]);
```
As you can see on the screen, even Intellisense doesn't propose me `saturate`, `desaturate`...
**Screenshots**  
![Intellisense](https://user-images.githubusercontent.com/29955402/107883637-5445d080-6ef0-11eb-8c52-06a0e40feb12.png)

## Context
- Jimp Version: 0.16.1
- Operating System: macOS Big Sur 11.2
- Node version: v14.15.1

## Failure Logs
```
$ npm start
>>> src/helpers/FilterManager.ts(95,17): error TS2322: Type '"saturate"' is not assignable to type 'ColorActionName'.
```

**Comment by anuragjain** [comment]
Any update on this? Having same issue.
I checked the code and colorActionName is not defined for lot of things like saturate, desaturate,grayscale etc.

https://github.com/oliver-moran/jimp/blob/53ff9d1266207f7f674233f465ec358274510511/packages/plugin-color/index.d.ts#L3

**Comment by daniellwdb** [comment]
Could we make this an enum and export it so it makes refactoring easier?

**Comment by hipstersmoothie** [comment]
Do whatever you can to fix the issue 😇
