### ISSUE TITLE
`getBuffer` expects a string, but it could also be a number - if using `AUTO` constant

### ISSUE THREAD

**Issue by olliechick** [jimp-dev/jimp#990]
The `getBuffer` function expects a string type for the parameter `mime`, but a number is actually a valid input - if it is the constant `AUTO`. 

https://github.com/oliver-moran/jimp/blob/7d3fc67abf1bcb4c502a1b404decafb31b2dd0a9/packages/core/src/utils/image-bitmap.js#L195

**Comment by olliechick** [comment]
I think changing the line to the below would fix it:

```
 * @param {(string|number)} mime the mime type of the image buffer to be created
```

**Comment by hipstersmoothie** [comment]
@olliechick want to submit a PR for that?
