### ISSUE TITLE
How do you  change the color palette of a .bmp and save a new copy?

### ISSUE THREAD

**Issue by j-masci** [jimp-dev/jimp#996]
# Expected Behavior

I would expect that after running this code, test-new.bmp would be different and probably more red than the original image.

```
import jimp from 'jimp';

const image = await jimp.read('test.bmp');

image.bitmap.palette = image.bitmap.palette.map(c => {
    c.red = 200;
    return c;
})

const copy = await image.writeAsync('test-new.bmp');
```

# Current Behavior

It looks identical to the original image.

## Steps to Reproduce

Use the code sample above with a test.bmp in the same folder.

## Context

- Jimp Version: "^0.16.1"
- Operating System: Windows
- Node version: 14.15.4

**Comment by j-masci** [comment]
It seems the .write method only reads from the buffer,  ie. image.bitmap.data. I don't see any way to set the color palette so that it updates the buffer.

**Comment by rzorzal-wa** [comment]
If you use a black color at your font, you can use this method to change the color for what you want:
```javascript
textImg.color([{ apply: 'xor', params: [color] }]);
```

**Comment by j-masci** [comment]
I'm not sure I understand tbh. what does this mean, black color at my font?

I need to redefine the color palette and then map each pixel color from the old palette to the closest color in the new palette. I would probably have to write my own function to map to the nearest color in a given palette but that's fine. The issue is that I can't set the palette on the bitmap to a new one and then save it (new palette is not taken into consideration when writing the the new file).

**Comment by hipstersmoothie** [comment]
What I would do is write the text to another jimp image of the same size, modify the color of that image, then blit it on top of your background
